import { Layout , Space , Radius, FontSize, Fonts } from "../../theme/tokens";
import { defineStyles } from "../../theme";
import { StyleSheet } from "react-native";

export const useStyles = defineStyles(({ colors: Colors }) => ({
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: Space.sm,
    maxWidth: Layout.contentWidth,
    paddingHorizontal: Space.md,
    paddingVertical: 10,
    width: "100%",
  },

  headerCopy: { flex: 1 },
  headerEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.2 },
  headerTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500" },
  modeSwitchWrap: {
    alignSelf: "center",
    maxWidth: Layout.contentWidth,
    paddingHorizontal: Space.md,
    paddingTop: Space.xxs,
    width: "100%",
  },
  container: {
    alignSelf: "center",
    maxWidth: Layout.contentWidth,
    paddingBottom: 108,
    paddingHorizontal: Space.md,
    width: "100%",
  },
  introRow: { alignItems: "center", flexDirection: "row", gap: 11, marginTop: 18 },
  stepBadge: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.control,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,

  },
  stepBadgeText: { color: Colors.primary, fontSize: FontSize.label, fontWeight: "500" },
  stepCopy: { flex: 1 },
  sectionTitle: { color: Colors.text, fontSize: FontSize.subtitle, fontWeight: "500" },
  sectionHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  boxChoices: { flexDirection: "row", gap: Space.xs, marginTop: Space.sm },
  boxModeRow: {
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: Space.xxs,
    marginTop: 7,
    padding: Space.xxs,

  },
  boxModeChoice: { alignItems: "center", borderRadius: Radius.small, flex: 1, justifyContent: "center", minHeight: 42, paddingHorizontal: Space.xs },
  boxModeChoiceSelected: { backgroundColor: Colors.surface3, borderColor: Colors.borderStrong, borderWidth: 1,  },
  boxModeText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", textAlign: "center" },
  boxModeTextSelected: { color: Colors.text },
  builderPanel: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    marginTop: Space.xs,
    padding: 9,

  },
  boxBuilderRow: { alignItems: "center", flexDirection: "row", gap: 6 },
  builderControl: {
    backgroundColor: Colors.surface2,
    borderColor: Colors.borderStrong,
    borderRadius: Radius.control,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 68,
    paddingHorizontal: 11,

  },
  builderShapeControl: { flex: 1.18 },
  builderLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  builderValue: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500", marginTop: 5 },
  builderChevron: { color: Colors.primary, fontSize: FontSize.caption },
  builderTimes: { color: Colors.primary, fontSize: FontSize.subtitle, fontWeight: "500" },
  addOnControl: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.borderStrong,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: Space.xs,
    minHeight: 58,
    paddingHorizontal: Space.sm,

  },
  addOnValue: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500", marginTop: Space.xxs },
  addOnVolumeCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: Space.xs,
    padding: 11,
  },
  addOnVolumeInput: {
    borderBottomColor: Colors.primary,
    borderBottomWidth: 2,
    color: Colors.text,
    fontSize: FontSize.title,
    fontWeight: "500",
    marginTop: 2,
    maxWidth: 130,
    padding: 0,
  },
  boxChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    minHeight: 68,
    paddingHorizontal: 11,
    paddingVertical: 10,

  },
  boxChoiceSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  boxSketch: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderColor: Colors.textMuted,
    borderRadius: 7,
    borderWidth: 2,
    height: 35,
    justifyContent: "center",
    width: 35,

  },
  boxSketchLarge: { height: 39, width: 39 },
  knockout: { borderColor: Colors.textSubtle, borderRadius: Radius.control, borderWidth: 1, height: 13, width: 13 },
  stampIcon: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderColor: Colors.textMuted,
    borderRadius: 7,
    borderStyle: "dashed",
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    width: 43,
  },
  stampIconText: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  boxChoiceCopy: { flex: 1, marginLeft: 9 },
  boxChoiceTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  boxChoiceHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  boxChoiceCheck: { color: Colors.primary, fontSize: FontSize.label, fontWeight: "500", minWidth: 15, textAlign: "right" },
  depthLabel: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1, marginTop: 14 },
  depthRow: { flexDirection: "row", gap: Space.xs, marginTop: 7 },
  depthChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 56,

  },
  depthChoiceSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  depthValue: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500" },
  depthValueSelected: { color: Colors.inverseText },
  depthVolume: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", marginTop: 2 },
  depthVolumeSelected: { color: Colors.inverseText },
  otherDepthChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: Space.xs,
    minHeight: 48,
    paddingHorizontal: 13,
  },
  otherDepthChoiceSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  otherDepthLabel: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  otherDepthHint: { color: Colors.textMuted, flex: 1, fontSize: FontSize.caption, marginLeft: Space.xs },
  selectedBoxCard: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    padding: Space.sm,

  },
  selectedBoxLabel: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  selectedBoxValue: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500", marginTop: 3 },
  selectedCapacity: { alignItems: "flex-end", marginLeft: Space.xs },
  selectedCapacityValue: { color: Colors.primary, fontSize: FontSize.subtitle, fontWeight: "500" },
  selectedCapacityLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.5 },
  markedCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: Space.sm,
    padding: Space.sm,

  },
  markedCopy: { flex: 1 },
  markedLabel: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  markedInput: {
    borderBottomColor: Colors.primary,
    borderBottomWidth: 2,
    color: Colors.text,
    fontSize: FontSize.heading,
    fontWeight: "500",
    marginTop: 3,
    maxWidth: 150,
    padding: 0,
  },
  markedPlaceholder: { color: Colors.textSubtle },
  markedUnit: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 3 },
  doneKeyboardButton: { backgroundColor: Colors.primary, borderRadius: Radius.control, paddingHorizontal: 14, paddingVertical: 10 },
  doneKeyboardButtonText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500" },
  boxHelpButton: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 9, minHeight: 34, paddingHorizontal: 3 },
  boxHelpButtonText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  boxHelpCard: { backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, padding: 11 },
  boxHelpText: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 15 },
  divider: { backgroundColor: Colors.border, height: StyleSheet.hairlineWidth, marginTop: 20 },
  wireList: { gap: 9, marginTop: Space.sm },
  wireCard: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    gap: 7,
    padding: Space.xs,

  },
  wireTopRow: { alignItems: "center", flexDirection: "row", gap: Space.xs },
  wireSizeButton: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 50,
    paddingHorizontal: Space.sm,
  },
  controlLabel: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.7 },
  controlValue: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500", marginTop: 2 },
  chevron: { color: Colors.textMuted, fontSize: FontSize.body, fontWeight: "500" },
  removeButton: { alignItems: "center", backgroundColor: Colors.errorSoft, borderRadius: Radius.control, height: 42, justifyContent: "center", width: 34 },
  removeButtonText: { color: Colors.error, fontSize: FontSize.section, fontWeight: "500", lineHeight: 23 },
  roleButton: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 47,
    paddingHorizontal: Space.sm,
  },
  roleCopy: { flex: 1 },
  roleValue: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500", marginTop: 2 },
  roleBadge: { backgroundColor: Colors.surface3, borderRadius: 7, marginRight: 10, paddingHorizontal: 7, paddingVertical: 5 },
  roleBadgeGround: { backgroundColor: Colors.successSoft },
  roleBadgeText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.5 },
  addWireButton: {
    alignItems: "center",
    borderColor: Colors.borderStrong,
    borderRadius: Radius.control,
    borderStyle: "dashed",
    borderWidth: 1,
    flexDirection: "row",
    gap: Space.xs,
    justifyContent: "center",
    marginTop: 10,
    minHeight: 48,
  },
  addWireIcon: { color: Colors.primary, fontSize: FontSize.subtitle, fontWeight: "500" },
  addWireText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  extraCard: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    marginTop: Space.sm,
    overflow: "hidden",
    paddingHorizontal: 13,

  },
  extraRow: { alignItems: "center", flexDirection: "row", minHeight: 67, paddingVertical: 9 },
  extraCopy: { flex: 1, paddingRight: 10 },
  extraTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  extraHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 3 },
  extraDivider: { backgroundColor: Colors.border, height: StyleSheet.hairlineWidth },
  smallStepper: { alignItems: "center", backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, flexDirection: "row" },
  smallStepButton: { alignItems: "center", height: 38, justifyContent: "center", width: 37 },
  smallStepText: { color: Colors.primary, fontSize: FontSize.body, fontWeight: "500" },
  smallStepValue: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500", minWidth: 25, textAlign: "center" },
  deviceSizeRow: { alignItems: "center", backgroundColor: Colors.surface2, borderRadius: Radius.control, flexDirection: "row", justifyContent: "space-between", marginBottom: 10, padding: 10 },
  deviceSizeValue: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500", marginTop: 2 },
  deviceHelp: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 13, marginBottom: 10, marginTop: -4 },
  toggle: { backgroundColor: Colors.surface3, borderRadius: Radius.control, height: 26, padding: 3, width: 46 },
  toggleOn: { backgroundColor: Colors.primary },
  toggleKnob: { backgroundColor: Colors.textMuted, borderRadius: Radius.control, height: 20, width: 20 },
  toggleKnobOn: { alignSelf: "flex-end", backgroundColor: Colors.inverseText },
  resultCard: {
    backgroundColor: Colors.successSoft,
    borderColor: Colors.success,
    borderRadius: Radius.large,
    borderWidth: 1,
    marginTop: 22,
    padding: 17,

  },
  resultCardFail: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  resultCardWaiting: { backgroundColor: Colors.surface, borderColor: Colors.borderStrong },
  resultTopRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  resultEyebrow: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.1 },
  resultStatus: { color: Colors.success, fontSize: FontSize.screen, fontWeight: "500", letterSpacing: 0.4 },
  resultStatusFail: { color: Colors.error },
  resultStatusWaiting: { color: Colors.textMuted, fontSize: FontSize.title },
  volumeBadge: { alignItems: "center", backgroundColor: Colors.surface3, borderColor: Colors.borderStrong, borderRadius: Radius.control, borderWidth: 1, minWidth: 82, paddingHorizontal: 10, paddingVertical: 7 },
  volumeBadgeValue: { color: Colors.text, fontSize: FontSize.subtitle, fontWeight: "500" },
  volumeBadgeLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.6 },
  meterTrack: { backgroundColor: Colors.bg, borderRadius: 7, height: 11, marginTop: Space.md, overflow: "hidden" },
  meterFill: { backgroundColor: Colors.success, borderRadius: 7, height: "100%" },
  meterFillFail: { backgroundColor: Colors.error },
  resultDetails: { borderTopColor: Colors.border, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", marginTop: 15, paddingTop: 14 },
  detailBlock: { flex: 1 },
  detailRule: { backgroundColor: Colors.border, marginHorizontal: Space.sm, width: 1 },
  detailLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  detailValue: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500", marginTop: 3 },
  detailCaption: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  breakdownButton: { alignItems: "center", borderTopColor: Colors.border, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", marginTop: 14, paddingTop: 13 },
  breakdownButtonText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  breakdownList: { gap: 7, marginTop: Space.sm },
  breakdownRow: { flexDirection: "row", justifyContent: "space-between" },
  breakdownLabel: { color: Colors.textMuted, fontSize: FontSize.caption },
  breakdownValue: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  codeNote: { backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.card, borderWidth: 1, marginTop: Space.sm, padding: 13 },
  codeNoteTitle: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  codeNoteText: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 16, marginTop: Space.xxs },
  liveResult: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: Colors.successSoft,
    borderColor: Colors.success,
    borderRadius: Radius.card,
    borderWidth: 1,
    bottom: 8,
    flexDirection: "row",
    maxWidth: 528,
    paddingHorizontal: 13,
    paddingVertical: 10,
    position: "absolute",
    width: "92%",

  },
  liveResultFail: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  liveResultWaiting: { backgroundColor: Colors.surface2, borderColor: Colors.borderStrong },
  liveResultCopy: { flex: 1 },
  liveResultStatus: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.4 },
  liveResultBox: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  liveResultArrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  pressed: { opacity: 0.78, transform: [{ scale: 0.98 }],  },
  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: { backgroundColor: Colors.overlay, bottom: 0, left: 0, position: "absolute", right: 0, top: 0 },
  sheet: { backgroundColor: Colors.surface, borderColor: Colors.border, borderTopLeftRadius: Radius.sheet, borderTopRightRadius: Radius.sheet, borderWidth: 1, paddingBottom: 18 },
  sheetHandle: { alignSelf: "center", backgroundColor: Colors.borderStrong, borderRadius: 3, height: 4, marginTop: 9, width: 42 },
  sheetHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", padding: Space.md },
  sheetEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1 },
  sheetTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500", marginTop: 2 },
  doneButton: { backgroundColor: Colors.primary, borderRadius: Radius.control, paddingHorizontal: 14, paddingVertical: 9 },
  doneButtonText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500" },
  builderOptions: { gap: Space.xs, paddingHorizontal: Space.md },
  builderOption: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 60,
    paddingHorizontal: 13,

  },
  builderOptionSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  builderOptionCopy: { flex: 1 },
  builderOptionTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  builderOptionHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 3 },
  builderOptionCheck: { color: Colors.primary, fontSize: FontSize.body, fontWeight: "500" },
  wireSizeGrid: { flexDirection: "row", flexWrap: "wrap", gap: Space.xs, paddingHorizontal: Space.md },
  wireSizeOption: { alignItems: "center", backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, justifyContent: "center", minHeight: 50, width: "22.9%" },
  wireSizeOptionSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  wireSizeOptionText: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500" },
  wireSizeOptionTextSelected: { color: Colors.inverseText },
  roleOptions: { gap: 9, paddingHorizontal: Space.md },
  roleOption: { alignItems: "center", backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: Radius.card, borderWidth: 1, flexDirection: "row", minHeight: 72, padding: Space.sm },
  roleOptionSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  roleOptionIcon: { alignItems: "center", backgroundColor: Colors.surface3, borderRadius: Radius.control, height: 40, justifyContent: "center", width: 40 },
  roleOptionIconGround: { backgroundColor: Colors.successSoft },
  roleOptionIconText: { color: Colors.primary, fontSize: FontSize.label, fontWeight: "500" },
  roleOptionCopy: { flex: 1, marginLeft: 11 },
  roleOptionTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  roleOptionHint: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 14, marginTop: 3 },
  roleOptionCheck: { color: Colors.primary, fontSize: FontSize.subtitle, fontWeight: "500" },
}));
