import { StyleSheet } from "react-native";

import { Colors, Effects } from "../../theme";

export const styles = StyleSheet.create({
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: 12,
    maxWidth: 560,
    paddingHorizontal: 16,
    paddingVertical: 10,
    width: "100%",
  },
  homeButton: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 10,
    ...Effects.controlRaised,
  },
  homeButtonText: { color: Colors.text, fontSize: 13, fontWeight: "800" },
  headerCopy: { flex: 1 },
  headerEyebrow: { color: Colors.primary, fontSize: 9, fontWeight: "900", letterSpacing: 1.2 },
  headerTitle: { color: Colors.text, fontSize: 21, fontWeight: "900" },
  modeSwitchWrap: {
    alignSelf: "center",
    maxWidth: 560,
    paddingHorizontal: 16,
    paddingTop: 4,
    width: "100%",
  },
  container: {
    alignSelf: "center",
    maxWidth: 560,
    paddingBottom: 108,
    paddingHorizontal: 16,
    width: "100%",
  },
  introRow: { alignItems: "center", flexDirection: "row", gap: 11, marginTop: 18 },
  stepBadge: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: 11,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
    ...Effects.recessed,
  },
  stepBadgeText: { color: Colors.primary, fontSize: 15, fontWeight: "900" },
  stepCopy: { flex: 1 },
  sectionTitle: { color: Colors.text, fontSize: 18, fontWeight: "900" },
  sectionHint: { color: Colors.textMuted, fontSize: 11, marginTop: 2 },
  boxChoices: { flexDirection: "row", gap: 8, marginTop: 12 },
  boxModeRow: {
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    marginTop: 7,
    padding: 4,
    ...Effects.recessed,
  },
  boxModeChoice: { alignItems: "center", borderRadius: 9, flex: 1, justifyContent: "center", minHeight: 42, paddingHorizontal: 8 },
  boxModeChoiceSelected: { backgroundColor: Colors.surface3, borderColor: Colors.borderStrong, borderWidth: 1, ...Effects.controlRaised },
  boxModeText: { color: Colors.textMuted, fontSize: 11, fontWeight: "800", textAlign: "center" },
  boxModeTextSelected: { color: Colors.text },
  builderPanel: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 8,
    padding: 9,
    ...Effects.surfaceRaised,
  },
  boxBuilderRow: { alignItems: "center", flexDirection: "row", gap: 6 },
  builderControl: {
    backgroundColor: Colors.surface2,
    borderColor: Colors.borderStrong,
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 68,
    paddingHorizontal: 11,
    ...Effects.controlRaised,
  },
  builderShapeControl: { flex: 1.18 },
  builderLabel: { color: Colors.textMuted, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  builderValue: { color: Colors.text, fontSize: 15, fontWeight: "900", marginTop: 5 },
  builderChevron: { color: Colors.primary, fontSize: 12 },
  builderTimes: { color: Colors.primary, fontSize: 18, fontWeight: "900" },
  addOnControl: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.borderStrong,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    minHeight: 58,
    paddingHorizontal: 12,
    ...Effects.controlRaised,
  },
  addOnValue: { color: Colors.text, fontSize: 14, fontWeight: "900", marginTop: 4 },
  addOnVolumeCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
    padding: 11,
  },
  addOnVolumeInput: {
    borderBottomColor: Colors.primary,
    borderBottomWidth: 2,
    color: Colors.text,
    fontSize: 25,
    fontWeight: "900",
    marginTop: 2,
    maxWidth: 130,
    padding: 0,
  },
  boxChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 15,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    minHeight: 68,
    paddingHorizontal: 11,
    paddingVertical: 10,
    ...Effects.controlRaised,
  },
  boxChoiceSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  boxSketch: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderColor: Colors.textMuted,
    borderRadius: 7,
    borderWidth: 2,
    height: 35,
    justifyContent: "center",
    width: 35,
    ...Effects.recessed,
  },
  boxSketchLarge: { height: 39, width: 39 },
  knockout: { borderColor: Colors.textSubtle, borderRadius: 10, borderWidth: 1, height: 13, width: 13 },
  stampIcon: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderColor: Colors.textMuted,
    borderRadius: 7,
    borderStyle: "dashed",
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    width: 43,
  },
  stampIconText: { color: Colors.primary, fontSize: 12, fontWeight: "900" },
  boxChoiceCopy: { flex: 1, marginLeft: 9 },
  boxChoiceTitle: { color: Colors.text, fontSize: 11, fontWeight: "900" },
  boxChoiceHint: { color: Colors.textMuted, fontSize: 9, marginTop: 2 },
  boxChoiceCheck: { color: Colors.primary, fontSize: 15, fontWeight: "900", minWidth: 15, textAlign: "right" },
  depthLabel: { color: Colors.textSubtle, fontSize: 9, fontWeight: "900", letterSpacing: 1, marginTop: 14 },
  depthRow: { flexDirection: "row", gap: 8, marginTop: 7 },
  depthChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 56,
    ...Effects.controlRaised,
  },
  depthChoiceSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  depthValue: { color: Colors.text, fontSize: 14, fontWeight: "900" },
  depthValueSelected: { color: Colors.inverseText },
  depthVolume: { color: Colors.textMuted, fontSize: 9, fontWeight: "700", marginTop: 2 },
  depthVolumeSelected: { color: "#4A380D" },
  otherDepthChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: 8,
    minHeight: 48,
    paddingHorizontal: 13,
  },
  otherDepthChoiceSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  otherDepthLabel: { color: Colors.text, fontSize: 12, fontWeight: "900" },
  otherDepthHint: { color: Colors.textMuted, flex: 1, fontSize: 9, marginLeft: 8 },
  selectedBoxCard: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    padding: 12,
    ...Effects.recessed,
  },
  selectedBoxLabel: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  selectedBoxValue: { color: Colors.text, fontSize: 12, fontWeight: "900", marginTop: 3 },
  selectedCapacity: { alignItems: "flex-end", marginLeft: 8 },
  selectedCapacityValue: { color: Colors.primary, fontSize: 18, fontWeight: "900" },
  selectedCapacityLabel: { color: Colors.textMuted, fontSize: 7, fontWeight: "900", letterSpacing: 0.5 },
  markedCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
    padding: 12,
    ...Effects.surfaceRaised,
  },
  markedCopy: { flex: 1 },
  markedLabel: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  markedInput: {
    borderBottomColor: Colors.primary,
    borderBottomWidth: 2,
    color: Colors.text,
    fontSize: 30,
    fontWeight: "900",
    marginTop: 3,
    maxWidth: 150,
    padding: 0,
  },
  markedPlaceholder: { color: Colors.textSubtle },
  markedUnit: { color: Colors.textMuted, fontSize: 10, marginTop: 3 },
  doneKeyboardButton: { backgroundColor: Colors.primary, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10 },
  doneKeyboardButtonText: { color: Colors.inverseText, fontSize: 12, fontWeight: "900" },
  boxHelpButton: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 9, minHeight: 34, paddingHorizontal: 3 },
  boxHelpButtonText: { color: Colors.textMuted, fontSize: 10, fontWeight: "800" },
  boxHelpCard: { backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: 11, borderWidth: 1, padding: 11 },
  boxHelpText: { color: Colors.textMuted, fontSize: 10, lineHeight: 15 },
  divider: { backgroundColor: Colors.border, height: StyleSheet.hairlineWidth, marginTop: 20 },
  wireList: { gap: 9, marginTop: 12 },
  wireCard: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 7,
    padding: 8,
    ...Effects.surfaceRaised,
  },
  wireTopRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  wireSizeButton: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 11,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 50,
    paddingHorizontal: 12,
  },
  controlLabel: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.7 },
  controlValue: { color: Colors.text, fontSize: 16, fontWeight: "900", marginTop: 2 },
  chevron: { color: Colors.textMuted, fontSize: 16, fontWeight: "900" },
  removeButton: { alignItems: "center", backgroundColor: Colors.errorSoft, borderRadius: 10, height: 42, justifyContent: "center", width: 34 },
  removeButtonText: { color: Colors.error, fontSize: 22, fontWeight: "700", lineHeight: 23 },
  roleButton: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 11,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 47,
    paddingHorizontal: 12,
  },
  roleCopy: { flex: 1 },
  roleValue: { color: Colors.text, fontSize: 12, fontWeight: "800", marginTop: 2 },
  roleBadge: { backgroundColor: Colors.surface3, borderRadius: 7, marginRight: 10, paddingHorizontal: 7, paddingVertical: 5 },
  roleBadgeGround: { backgroundColor: "#244430" },
  roleBadgeText: { color: Colors.textMuted, fontSize: 7, fontWeight: "900", letterSpacing: 0.5 },
  addWireButton: {
    alignItems: "center",
    borderColor: Colors.borderStrong,
    borderRadius: 13,
    borderStyle: "dashed",
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginTop: 10,
    minHeight: 48,
  },
  addWireIcon: { color: Colors.primary, fontSize: 19, fontWeight: "900" },
  addWireText: { color: Colors.text, fontSize: 13, fontWeight: "800" },
  extraCard: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    overflow: "hidden",
    paddingHorizontal: 13,
    ...Effects.surfaceRaised,
  },
  extraRow: { alignItems: "center", flexDirection: "row", minHeight: 67, paddingVertical: 9 },
  extraCopy: { flex: 1, paddingRight: 10 },
  extraTitle: { color: Colors.text, fontSize: 13, fontWeight: "900" },
  extraHint: { color: Colors.textMuted, fontSize: 10, marginTop: 3 },
  extraDivider: { backgroundColor: Colors.border, height: StyleSheet.hairlineWidth },
  smallStepper: { alignItems: "center", backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: 10, borderWidth: 1, flexDirection: "row" },
  smallStepButton: { alignItems: "center", height: 38, justifyContent: "center", width: 37 },
  smallStepText: { color: Colors.primary, fontSize: 17, fontWeight: "900" },
  smallStepValue: { color: Colors.text, fontSize: 16, fontWeight: "900", minWidth: 25, textAlign: "center" },
  deviceSizeRow: { alignItems: "center", backgroundColor: Colors.surface2, borderRadius: 10, flexDirection: "row", justifyContent: "space-between", marginBottom: 10, padding: 10 },
  deviceSizeValue: { color: Colors.text, fontSize: 15, fontWeight: "900", marginTop: 2 },
  deviceHelp: { color: Colors.textMuted, fontSize: 9, lineHeight: 13, marginBottom: 10, marginTop: -4 },
  toggle: { backgroundColor: Colors.surface3, borderRadius: 13, height: 26, padding: 3, width: 46 },
  toggleOn: { backgroundColor: Colors.primary },
  toggleKnob: { backgroundColor: Colors.textMuted, borderRadius: 10, height: 20, width: 20 },
  toggleKnobOn: { alignSelf: "flex-end", backgroundColor: Colors.inverseText },
  resultCard: {
    backgroundColor: "#17251F",
    borderColor: "#486D5D",
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 22,
    padding: 17,
    ...Effects.surfaceRaised,
  },
  resultCardFail: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  resultCardWaiting: { backgroundColor: Colors.surface, borderColor: Colors.borderStrong },
  resultTopRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  resultEyebrow: { color: Colors.textMuted, fontSize: 9, fontWeight: "900", letterSpacing: 1.1 },
  resultStatus: { color: "#76C69E", fontSize: 35, fontWeight: "900", letterSpacing: 0.4 },
  resultStatusFail: { color: Colors.error },
  resultStatusWaiting: { color: Colors.textMuted, fontSize: 23 },
  volumeBadge: { alignItems: "center", backgroundColor: Colors.surface3, borderColor: Colors.borderStrong, borderRadius: 13, borderWidth: 1, minWidth: 82, paddingHorizontal: 10, paddingVertical: 7 },
  volumeBadgeValue: { color: Colors.text, fontSize: 18, fontWeight: "900" },
  volumeBadgeLabel: { color: Colors.textMuted, fontSize: 7, fontWeight: "900", letterSpacing: 0.6 },
  meterTrack: { backgroundColor: Colors.bg, borderRadius: 7, height: 11, marginTop: 16, overflow: "hidden" },
  meterFill: { backgroundColor: "#62A982", borderRadius: 7, height: "100%" },
  meterFillFail: { backgroundColor: Colors.error },
  resultDetails: { borderTopColor: "rgba(255,255,255,0.09)", borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", marginTop: 15, paddingTop: 14 },
  detailBlock: { flex: 1 },
  detailRule: { backgroundColor: "rgba(255,255,255,0.10)", marginHorizontal: 12, width: 1 },
  detailLabel: { color: Colors.textMuted, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  detailValue: { color: Colors.text, fontSize: 14, fontWeight: "900", marginTop: 3 },
  detailCaption: { color: Colors.textMuted, fontSize: 9, marginTop: 2 },
  breakdownButton: { alignItems: "center", borderTopColor: "rgba(255,255,255,0.09)", borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", justifyContent: "space-between", marginTop: 14, paddingTop: 13 },
  breakdownButtonText: { color: Colors.text, fontSize: 11, fontWeight: "800" },
  breakdownList: { gap: 7, marginTop: 12 },
  breakdownRow: { flexDirection: "row", justifyContent: "space-between" },
  breakdownLabel: { color: Colors.textMuted, fontSize: 10 },
  breakdownValue: { color: Colors.text, fontSize: 10, fontWeight: "800" },
  codeNote: { backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 14, borderWidth: 1, marginTop: 12, padding: 13 },
  codeNoteTitle: { color: Colors.primary, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 },
  codeNoteText: { color: Colors.textMuted, fontSize: 11, lineHeight: 16, marginTop: 4 },
  liveResult: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#192B23",
    borderColor: "#486D5D",
    borderRadius: 15,
    borderWidth: 1,
    bottom: 8,
    flexDirection: "row",
    maxWidth: 528,
    paddingHorizontal: 13,
    paddingVertical: 10,
    position: "absolute",
    width: "92%",
    ...Effects.surfaceRaised,
  },
  liveResultFail: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  liveResultWaiting: { backgroundColor: Colors.surface2, borderColor: Colors.borderStrong },
  liveResultCopy: { flex: 1 },
  liveResultStatus: { color: Colors.text, fontSize: 12, fontWeight: "900", letterSpacing: 0.4 },
  liveResultBox: { color: Colors.textMuted, fontSize: 8, marginTop: 2 },
  liveResultArrow: { color: Colors.primary, fontSize: 10, fontWeight: "900" },
  pressed: { opacity: 0.78, transform: [{ scale: 0.98 }], ...Effects.pressed },
  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: { backgroundColor: "rgba(0,0,0,0.70)", bottom: 0, left: 0, position: "absolute", right: 0, top: 0 },
  sheet: { backgroundColor: Colors.surface, borderColor: Colors.border, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, paddingBottom: 18 },
  sheetHandle: { alignSelf: "center", backgroundColor: Colors.borderStrong, borderRadius: 3, height: 4, marginTop: 9, width: 42 },
  sheetHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", padding: 16 },
  sheetEyebrow: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  sheetTitle: { color: Colors.text, fontSize: 20, fontWeight: "900", marginTop: 2 },
  doneButton: { backgroundColor: Colors.primary, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 9 },
  doneButtonText: { color: Colors.inverseText, fontSize: 12, fontWeight: "900" },
  builderOptions: { gap: 8, paddingHorizontal: 16 },
  builderOption: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 60,
    paddingHorizontal: 13,
    ...Effects.controlRaised,
  },
  builderOptionSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  builderOptionCopy: { flex: 1 },
  builderOptionTitle: { color: Colors.text, fontSize: 13, fontWeight: "900" },
  builderOptionHint: { color: Colors.textMuted, fontSize: 9, marginTop: 3 },
  builderOptionCheck: { color: Colors.primary, fontSize: 17, fontWeight: "900" },
  wireSizeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingHorizontal: 16 },
  wireSizeOption: { alignItems: "center", backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: 11, borderWidth: 1, justifyContent: "center", minHeight: 50, width: "22.9%" },
  wireSizeOptionSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  wireSizeOptionText: { color: Colors.text, fontSize: 15, fontWeight: "900" },
  wireSizeOptionTextSelected: { color: Colors.inverseText },
  roleOptions: { gap: 9, paddingHorizontal: 16 },
  roleOption: { alignItems: "center", backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: 14, borderWidth: 1, flexDirection: "row", minHeight: 72, padding: 12 },
  roleOptionSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  roleOptionIcon: { alignItems: "center", backgroundColor: Colors.surface3, borderRadius: 10, height: 40, justifyContent: "center", width: 40 },
  roleOptionIconGround: { backgroundColor: "#244430" },
  roleOptionIconText: { color: Colors.primary, fontSize: 14, fontWeight: "900" },
  roleOptionCopy: { flex: 1, marginLeft: 11 },
  roleOptionTitle: { color: Colors.text, fontSize: 13, fontWeight: "900" },
  roleOptionHint: { color: Colors.textMuted, fontSize: 10, lineHeight: 14, marginTop: 3 },
  roleOptionCheck: { color: Colors.primary, fontSize: 18, fontWeight: "900" },
});
