import { StyleSheet } from "react-native";
import { Colors as C } from "../../theme";

export const previewStyles = StyleSheet.create({
  stage: {
    backgroundColor: "#0E1318",
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#33414C",
  },
  guideButton: {
    minHeight: 44,
    justifyContent: "center",
    marginBottom: 6,
    paddingHorizontal: 2,
  },
  guideNavigation: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: C.border, marginBottom: 8 },
  controls: { minHeight: 56, marginBottom: 12 },
  tabs: {
    flexDirection: "row",
    height: 56,
    padding: 4,
    gap: 4,
    backgroundColor: C.bg,
    borderRadius: 14,
  },
  tab: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  tabText: { fontSize: 15, fontWeight: "700", color: C.textMuted },
  steps: { flexDirection: "row", flexWrap: "wrap", gap: 4 },
  step: {
    flexGrow: 1,
    flexBasis: "28%",
    minHeight: 56,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bg,
  },
  active: { backgroundColor: C.primarySoft, borderColor: C.primaryMuted },
  stepNumber: { fontSize: 10, fontWeight: "700", color: C.textSubtle },
  stepName: { fontSize: 12, fontWeight: "700", color: C.textMuted },
  amber: { color: C.primary },
  calculation: {
    color: C.text,
    fontSize: 22,
    fontWeight: "700",
    lineHeight: 30,
  },
  summary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 14,
  },
  summaryText: { flex: 1, minWidth: 0 },
  legend: { color: C.textMuted, fontSize: 11, lineHeight: 17 },
  copy: {
    minHeight: 44,
    minWidth: 76,
    paddingHorizontal: 10,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: C.surface3,
    borderWidth: 1,
    borderColor: C.border,
  },
  copyText: { color: C.text, fontWeight: "700", fontSize: 13 },
  caption: { minHeight: 80, paddingTop: 12 },
  markList: { gap: 8, paddingTop: 12 },
  markRows: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  markPosition: { flexBasis: 110, flexGrow: 1, gap: 3, padding: 10, borderRadius: 10, borderWidth: 1, borderColor: C.primaryMuted, backgroundColor: C.primarySoft },
  markMeasurement: { color: C.primary, fontSize: 18, lineHeight: 25, fontWeight: "700" },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: C.border,
  },
  textButton: { minHeight: 44, justifyContent: "center", paddingHorizontal: 8 },
  guideText: { color: C.textMuted, fontSize: 13, fontWeight: "500" },
  helpText: { color: C.textMuted, fontSize: 13, fontWeight: "600" },
  hint: { color: C.textMuted, fontSize: 11, lineHeight: 17, paddingTop: 4 },
  captionText: { color: C.textMuted, fontSize: 13, lineHeight: 20 },
});
