import { Space , Radius, FontSize } from "../../theme/tokens";
import { defineStyles } from "../../theme";

export const usePreviewStyles = defineStyles(({ colors: Colors }) => ({
  stage: {
    backgroundColor: Colors.surface2,
    borderRadius: Radius.card,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.border,
  },
  guideButton: {
    minHeight: 44,
    justifyContent: "center",
    marginBottom: 6,
    paddingHorizontal: 2,
  },
  guideNavigation: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: Colors.border, marginBottom: Space.xs },
  controls: { minHeight: 56, marginBottom: Space.sm },
  tabs: {
    flexDirection: "row",
    height: 56,
    padding: Space.xxs,
    gap: Space.xxs,
    backgroundColor: Colors.bg,
    borderRadius: Radius.card,
  },
  tab: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: Radius.control,
  },
  tabText: { fontSize: FontSize.label, fontWeight: "500", color: Colors.textMuted },
  steps: { flexDirection: "row", flexWrap: "wrap", gap: Space.xxs },
  step: {
    flexGrow: 1,
    flexBasis: "28%",
    minHeight: 56,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    borderRadius: Radius.control,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bg,
  },
  active: { backgroundColor: Colors.primarySoft, borderColor: Colors.primaryMuted },
  stepNumber: { fontSize: FontSize.caption, fontWeight: "500", color: Colors.textSubtle },
  stepName: { fontSize: FontSize.caption, fontWeight: "500", color: Colors.textMuted },
  amber: { color: Colors.primary },
  calculation: {
    color: Colors.text,
    fontSize: FontSize.section,
    fontWeight: "500",
    lineHeight: 30,
  },
  summary: {
    flexDirection: "row",
    alignItems: "center",
    gap: Space.xs,
    marginTop: 14,
  },
  summaryText: { flex: 1, minWidth: 0 },
  legend: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 17 },
  copy: {
    minHeight: 44,
    minWidth: 76,
    paddingHorizontal: 10,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: Radius.control,
    backgroundColor: Colors.surface3,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  copyText: { color: Colors.text, fontWeight: "500", fontSize: FontSize.caption },
  caption: { minHeight: 80, paddingTop: Space.sm },
  markList: { gap: Space.xs, paddingTop: Space.sm },
  markRows: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  markPosition: { flexBasis: 110, flexGrow: 1, gap: 3, padding: 10, borderRadius: Radius.control, borderWidth: 1, borderColor: Colors.primaryMuted, backgroundColor: Colors.primarySoft },
  markMeasurement: { color: Colors.primary, fontSize: FontSize.subtitle, lineHeight: 25, fontWeight: "500" },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  textButton: { minHeight: 44, justifyContent: "center", paddingHorizontal: Space.xs },
  guideText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  helpText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "600" },
  hint: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 17, paddingTop: Space.xxs },
  captionText: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 20 },
}));
