import { Layout , Space , Radius, FontSize, Fonts } from "../../theme/tokens";
import { defineStyles } from "../../theme";
export const useStyles = defineStyles(({ colors: Colors }) => ({
  safe: { flex: 1, backgroundColor: Colors.bg },
  header: {
    width: "100%",
    maxWidth: Layout.contentWidth,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    padding: Space.sm,
    gap: Space.sm,
  },

  headerTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500" },
  changeBend: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", textAlign: "center", lineHeight: 18 },
  fitWarning: { borderWidth: 1, borderColor: Colors.primaryMuted, borderRadius: Radius.card, padding: 14, gap: 10, backgroundColor: Colors.primarySoft },
  fitBody: { color: Colors.text, fontSize: FontSize.caption, lineHeight: 20 },
  fitReminder: { backgroundColor: Colors.surface, borderColor: Colors.border },
  title: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.title, fontWeight: "500" },
  eyebrow: {
    color: Colors.primary,
    fontSize: FontSize.caption,
    fontWeight: "500",
    letterSpacing: 1.2,
  },
  body: {
    width: "100%",
    maxWidth: Layout.contentWidth,
    alignSelf: "center",
    padding: Space.md,
    gap: 14,
    paddingBottom: Space.xl,
  },
  row: { flexDirection: "row", alignItems: "center", gap: Space.xs },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: Space.xs },
  grow: { flex: 1 },
  card: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderWidth: 1,
    borderRadius: Radius.large,
    padding: Space.md,
    gap: Space.sm,

  },
  button: {
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: Radius.control,
    backgroundColor: Colors.surface3,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",

  },
  selected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  primary: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  text: { color: Colors.text, fontSize: FontSize.label, fontWeight: "600" },
  muted: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 18 },
  amber: { color: Colors.primary },
  inverse: { color: Colors.inverseText, fontWeight: "500" },
  inputTile: {
    flexGrow: 1,
    flexBasis: 130,
    backgroundColor: Colors.bg,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    padding: 14,
    minHeight: 78,
    gap: 6,
  },
  inputValue: { color: Colors.text, fontSize: FontSize.title, fontWeight: "500" },
  tabs: {
    flexDirection: "row",
    padding: Space.xxs,
    gap: Space.xxs,
    backgroundColor: Colors.bg,
    borderRadius: Radius.card,
  },
  tab: {
    flex: 1,
    minHeight: 44,
    borderRadius: Radius.control,
    justifyContent: "center",
    alignItems: "center",
  },
  result: { fontSize: FontSize.display, fontWeight: "500", color: Colors.text, letterSpacing: -1 },
  label: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  divider: { height: 1, backgroundColor: Colors.border },
  locationButton: {
    minHeight: 48,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: Colors.borderStrong,
    borderRadius: Radius.control,
    paddingVertical: 10,
    paddingHorizontal: Space.sm,
    gap: Space.xs,
  },
  savedLocation: {
    flexDirection: "row", alignItems: "center", gap: Space.xs,
    borderWidth: 1, borderColor: Colors.borderStrong, borderRadius: Radius.control,
    backgroundColor: Colors.bg, paddingLeft: 14, paddingRight: 6, paddingVertical: 6,
  },
  locationEdit: { minHeight: 44, minWidth: 52, justifyContent: "center", alignItems: "center" },
  locationIcon: { color: Colors.primary, fontSize: FontSize.subtitle, fontWeight: "500" },
  locationText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500", flexShrink: 1 },
  warning: {
    color: Colors.textMuted,
    fontSize: FontSize.caption,
    lineHeight: 18,
    borderLeftWidth: 2,
    borderLeftColor: Colors.primaryMuted,
    paddingLeft: 10,
  },
  overlay: { flex: 1, backgroundColor: Colors.overlay, justifyContent: "flex-end" },
  sheet: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: Radius.sheet,
    borderTopRightRadius: Radius.sheet,
    borderWidth: 1,
    borderColor: Colors.border,
    maxHeight: "90%",
    width: "100%",
    maxWidth: Layout.contentWidth,
    alignSelf: "center",
    padding: 20,
    gap: Space.md,
  },
  sheetBody: { gap: Space.md, paddingBottom: Space.lg },
  input: {
    backgroundColor: Colors.bg,
    color: Colors.text,
    fontSize: FontSize.heading,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    borderRadius: Radius.control,
    padding: Space.md,
    minHeight: 66,
  },
  error: { color: Colors.error, fontSize: FontSize.caption, lineHeight: 19 },
  step: { color: Colors.text, fontSize: FontSize.label, lineHeight: 22 },
}));
