import { StyleSheet } from "react-native";
import { Colors as C, Effects } from "../../theme";
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  header: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    gap: 12,
  },
  homeButton: { width: 52, minHeight: 48, alignItems: "center", justifyContent: "center", borderRadius: 12, borderWidth: 1, borderColor: C.border, backgroundColor: C.surface3 },
  homeIcon: { color: C.text, fontSize: 22, lineHeight: 24 },
  homeLabel: { color: C.textMuted, fontSize: 10, fontWeight: "600" },
  headerTitle: { color: C.text, fontSize: 21, fontWeight: "800" },
  changeBend: { color: C.primary, fontSize: 12, fontWeight: "700", textAlign: "center", lineHeight: 18 },
  fitWarning: { borderWidth: 1, borderColor: C.primaryMuted, borderRadius: 14, padding: 14, gap: 10, backgroundColor: C.primarySoft },
  fitBody: { color: C.text, fontSize: 13, lineHeight: 20 },
  fitReminder: { backgroundColor: C.surface, borderColor: C.border },
  title: { color: C.text, fontSize: 23, fontWeight: "800" },
  eyebrow: {
    color: C.primary,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  body: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    padding: 16,
    gap: 14,
    paddingBottom: 32,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  grow: { flex: 1 },
  card: {
    backgroundColor: C.surface,
    borderColor: C.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    gap: 12,
    ...Effects.surfaceRaised,
  },
  button: {
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: C.surface3,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: "center",
    justifyContent: "center",
    ...Effects.controlRaised,
  },
  selected: { backgroundColor: C.primarySoft, borderColor: C.primary },
  primary: { backgroundColor: C.primary, borderColor: C.primary },
  text: { color: C.text, fontSize: 15, fontWeight: "600" },
  muted: { color: C.textMuted, fontSize: 12, lineHeight: 18 },
  amber: { color: C.primary },
  inverse: { color: C.inverseText, fontWeight: "800" },
  inputTile: {
    flexGrow: 1,
    flexBasis: 130,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 14,
    padding: 14,
    minHeight: 78,
    gap: 6,
  },
  inputValue: { color: C.text, fontSize: 26, fontWeight: "700" },
  tabs: {
    flexDirection: "row",
    padding: 4,
    gap: 4,
    backgroundColor: C.bg,
    borderRadius: 14,
  },
  tab: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  result: { fontSize: 52, fontWeight: "800", color: C.text, letterSpacing: -1 },
  label: { color: C.primary, fontSize: 13, fontWeight: "700" },
  divider: { height: 1, backgroundColor: C.border },
  locationButton: {
    minHeight: 48,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: C.borderStrong,
    borderRadius: 13,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 8,
  },
  savedLocation: {
    flexDirection: "row", alignItems: "center", gap: 8,
    borderWidth: 1, borderColor: C.borderStrong, borderRadius: 13,
    backgroundColor: C.bg, paddingLeft: 14, paddingRight: 6, paddingVertical: 6,
  },
  locationEdit: { minHeight: 44, minWidth: 52, justifyContent: "center", alignItems: "center" },
  locationIcon: { color: C.primary, fontSize: 19, fontWeight: "900" },
  locationText: { color: C.text, fontSize: 13, fontWeight: "800", flexShrink: 1 },
  warning: {
    color: C.textMuted,
    fontSize: 12,
    lineHeight: 18,
    borderLeftWidth: 2,
    borderLeftColor: C.primaryMuted,
    paddingLeft: 10,
  },
  overlay: { flex: 1, backgroundColor: "#0009", justifyContent: "flex-end" },
  sheet: {
    backgroundColor: C.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: C.border,
    maxHeight: "90%",
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    padding: 20,
    gap: 16,
  },
  sheetBody: { gap: 16, paddingBottom: 24 },
  input: {
    backgroundColor: C.bg,
    color: C.text,
    fontSize: 28,
    borderWidth: 1,
    borderColor: C.borderStrong,
    borderRadius: 12,
    padding: 16,
    minHeight: 66,
  },
  error: { color: C.error, fontSize: 13, lineHeight: 19 },
  step: { color: C.text, fontSize: 14, lineHeight: 22 },
});
