/** Neutral Spanish for U.S. jobsites. Units and product identifiers are not translated. */
export const commonEs: Record<string, string> = {
  "Add numbers": "Sumar",
  "Done": "Listo", "Cancel": "Cancelar", "Clear": "Borrar", "Back": "Atrás", "Save": "Guardar", "Delete": "Eliminar", "Close": "Cerrar", "Continue": "Continuar",
  "Edit": "Editar", "Add": "Agregar", "Remove": "Quitar", "Copy": "Copiar", "Copied": "Copiado", "Share": "Compartir", "Undo": "Deshacer", "Undo removal": "Deshacer eliminación",
  "Settings": "Ajustes", "Close settings": "Cerrar ajustes", "Open app settings": "Abrir ajustes", "Return to toolbox home": "Volver al inicio",
  "What do you need?": "¿Qué necesitas?", "TOOLS": "HERRAMIENTAS", "READY OFFLINE": "DISPONIBLE SIN CONEXIÓN", "NEW": "NUEVO",
  "Workpad": "Calculadora", "Panel Colors": "Colores del tablero", "Jobsite Lists": "Listas de trabajo", "Fill Guide": "Guía de llenado", "Wire Guide": "Guía de conductores", "Trade Talk": "Diccionario", "Bending": "Doblado",
  "Measurements and field math": "Medidas y cálculos de obra", "Circuit phase and wire color": "Fase y color del conductor", "Job notes and material lists": "Notas y listas de materiales", "Conduit capacity and sizing": "Llenado y tamaño de tubería", "Ampacity and conductor limits": "Ampacidad y límites del conductor", "Electrical terms and jobsite slang": "Términos eléctricos y de obra", "Bend marks and pipe layouts": "Marcas y trazado de dobleces", "Opens {{title}}": "Abrir {{title}}",
  "Make it yours.": "A tu gusto.", "One look, across every tool. Your choice is saved on this device.": "Un mismo estilo en todas las herramientas. Tu elección se guarda en este dispositivo.",
  "LANGUAGE": "IDIOMA", "App language": "Idioma de la aplicación", "Automatic": "Automático", "Follows your phone’s supported language. You can choose a different language here.": "Sigue el idioma compatible del teléfono. Aquí puedes elegir otro idioma.", "Language changes labels, not units, electrical rules, or your own notes.": "El idioma cambia los textos, no las unidades, las reglas eléctricas ni tus notas.",
  "APPEARANCE": "APARIENCIA", "Appearance mode": "Modo de apariencia", "System": "Sistema", "Light": "Claro", "Dark": "Oscuro", "{{mode}} appearance": "Apariencia: {{mode}}", "Follows your device’s light or dark appearance.": "Sigue la apariencia clara u oscura del dispositivo.", "{{mode}} appearance stays on until you change it.": "El modo {{mode}} se mantiene hasta que lo cambies.",
  "COLOR THEME": "TEMA DE COLOR", "Color theme": "Tema de color", "{{name}} theme": "Tema {{name}}", "Jobsite": "Obra", "Studio": "Estudio", "Save again": "Volver a guardar",
  "SUPPORT & DATA": "AYUDA Y DATOS", "Backup & restore": "Copia de seguridad", "Keep a copy of saved work. Restore it when needed.": "Guarda una copia de tu trabajo y restáurala cuando la necesites.", "Help & app information": "Ayuda e información", "Getting started, privacy, and report a problem.": "Primeros pasos, privacidad y reporte de problemas.", "Version": "Versión", "Build": "Compilación", "Browser preview": "Vista previa web", "Installed build": "Aplicación instalada",
  "Saving…": "Guardando…", "Loading {{label}}…": "Cargando {{label}}…", "{{label}} couldn't be loaded. Your saved data is unchanged.": "No se pudo cargar {{label}}. Tus datos guardados no cambiaron.", "Changes aren't saved on this device. Retry saving.": "Los cambios no se guardaron en este dispositivo. Intenta guardarlos de nuevo.", "Retry loading": "Volver a cargar", "Retry saving": "Volver a guardar",
  "Appearance settings took too long to load. Choose a theme to save a new preference.": "La apariencia tardó demasiado en cargar. Elige un tema para guardar una nueva preferencia.", "Couldn’t load appearance. Choose a theme to save a new preference.": "No se pudo cargar la apariencia. Elige un tema para guardar una nueva preferencia.", "Theme changed, but couldn’t be saved. Try saving again.": "La preferencia cambió, pero no se guardó. Intenta guardarla de nuevo.",
  "YOUR SAVED WORK": "TU TRABAJO GUARDADO", "Backup restored": "Copia restaurada", "Previous work recovered": "Trabajo anterior recuperado", "Saved data ready": "Datos guardados disponibles", "Your saved work and settings are ready. Unfinished entry drafts were cleared.": "Tu trabajo y ajustes guardados están listos. Se borraron los borradores sin terminar.", "An interrupted restore was canceled. Your previous saved data was recovered.": "Se canceló una restauración interrumpida y se recuperaron tus datos anteriores.", "Saved data is ready again. Check your lists and settings before continuing.": "Los datos están disponibles de nuevo. Revisa tus listas y ajustes antes de continuar.",
  "Checking saved work": "Revisando datos guardados", "Protecting your saved work": "Protegiendo tus datos", "Retry recovery": "Reintentar recuperación", "Saved data could not be checked or recovered. Keep the app installed and retry. Your saved work has not been reset.": "No se pudieron revisar o recuperar los datos. No desinstales la aplicación e inténtalo de nuevo. Tu trabajo guardado no se ha restablecido.",
};
