import { StyleSheet } from "react-native";

import { Colors, Effects } from "../../theme";

export const styles = StyleSheet.create({
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: 12,
    maxWidth: 560,
    paddingHorizontal: 16,
    paddingVertical: 10,
    width: "100%",
  },
  homeButton: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 10,
    ...Effects.controlRaised,
  },
  homeButtonText: { color: Colors.text, fontSize: 13, fontWeight: "800" },
  headerCopy: { flex: 1 },
  headerEyebrow: { color: Colors.primary, fontSize: 9, fontWeight: "900", letterSpacing: 1.2 },
  headerTitle: { color: Colors.text, fontSize: 21, fontWeight: "900" },
  container: {
    alignSelf: "center",
    maxWidth: 560,
    paddingBottom: 34,
    paddingHorizontal: 16,
    width: "100%",
  },
  heroCard: {
    alignItems: "center",
    backgroundColor: "#181F28",
    borderColor: Colors.borderStrong,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginTop: 6,
    overflow: "hidden",
    padding: 14,
    position: "relative",
    ...Effects.surfaceRaised,
  },
  heroBolt: {
    alignItems: "center",
    backgroundColor: Colors.primary,
    borderRadius: 13,
    height: 46,
    justifyContent: "center",
    transform: [{ rotate: "-4deg" }],
    width: 46,
    ...Effects.primaryRaised,
  },
  heroBoltText: { color: Colors.inverseText, fontSize: 27, fontWeight: "900" },
  heroCopy: { flex: 1 },
  heroTitle: { color: Colors.text, fontSize: 17, fontWeight: "900" },
  heroHint: { color: Colors.textMuted, fontSize: 10, marginTop: 3 },
  speechMarks: { bottom: -12, opacity: 0.08, position: "absolute", right: 8 },
  speechMarksText: { color: Colors.primary, fontSize: 60, fontWeight: "900" },
  searchWrap: {
    alignItems: "center",
    backgroundColor: "#0E1318",
    borderColor: Colors.primaryMuted,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    marginTop: 13,
    minHeight: 57,
    paddingHorizontal: 12,
    ...Effects.recessed,
  },
  searchIcon: { color: Colors.primary, fontSize: 25, fontWeight: "900" },
  searchInput: { color: Colors.text, flex: 1, fontSize: 14, fontWeight: "700", minHeight: 52, outlineWidth: 0 },
  clearButton: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderRadius: 10,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  clearButtonText: { color: Colors.text, fontSize: 22, fontWeight: "700", lineHeight: 23 },
  searchSection: { marginTop: 18 },
  sectionRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 20 },
  sectionEyebrow: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1.05 },
  sectionTitle: { color: Colors.text, fontSize: 17, fontWeight: "900", marginTop: 2 },
  resultCount: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  entryCount: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  dailyCard: {
    backgroundColor: "#302711",
    borderColor: Colors.primaryMuted,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 14,
    overflow: "hidden",
    padding: 16,
    ...Effects.surfaceRaised,
  },
  dailyTopRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  dailyBadge: { backgroundColor: Colors.primary, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 },
  dailyBadgeText: { color: Colors.inverseText, fontSize: 7, fontWeight: "900", letterSpacing: 0.8 },
  dailyArrow: { color: Colors.primary, fontSize: 18, fontWeight: "900" },
  dailyTerm: { color: Colors.text, fontSize: 30, fontWeight: "900", letterSpacing: -0.5, marginTop: 12 },
  dailyOfficial: { color: Colors.primary, fontSize: 11, fontWeight: "900", marginTop: 2 },
  dailyDefinition: { color: Colors.textMuted, fontSize: 10, lineHeight: 15, marginTop: 8 },
  quizProgress: { color: Colors.textSubtle, fontSize: 9, fontWeight: "900" },
  quizCard: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 10,
    padding: 14,
    ...Effects.surfaceRaised,
  },
  quizPrompt: { color: Colors.text, fontSize: 14, fontWeight: "900", lineHeight: 20 },
  quizAnswers: { gap: 7, marginTop: 12 },
  quizAnswer: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 11,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 47,
    paddingHorizontal: 10,
    ...Effects.controlRaised,
  },
  quizAnswerCorrect: { backgroundColor: "#173126", borderColor: "#4C8A6C" },
  quizAnswerIncorrect: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  answerLetter: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderRadius: 8,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  answerLetterCorrect: { backgroundColor: "#4C8A6C" },
  answerLetterIncorrect: { backgroundColor: Colors.error },
  answerLetterText: { color: Colors.text, fontSize: 10, fontWeight: "900" },
  quizAnswerText: { color: Colors.text, flex: 1, fontSize: 11, fontWeight: "800" },
  answerMark: { color: "#72C69B", fontSize: 17, fontWeight: "900" },
  answerMarkIncorrect: { color: Colors.error, fontSize: 19, fontWeight: "900" },
  quizFeedback: { alignItems: "center", flexDirection: "row", gap: 10, justifyContent: "space-between", marginTop: 11 },
  quizFeedbackTitle: { color: Colors.textMuted, flex: 1, fontSize: 9, fontWeight: "800" },
  nextQuizButton: { backgroundColor: Colors.primarySoft, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 },
  nextQuizText: { color: Colors.primary, fontSize: 9, fontWeight: "900" },
  savedSection: { marginTop: 20 },
  filterRow: { gap: 7, paddingBottom: 3, paddingRight: 8, paddingTop: 10 },
  filterChip: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 13,
    ...Effects.controlRaised,
  },
  filterChipSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary, ...Effects.primaryRaised },
  filterChipText: { color: Colors.textMuted, fontSize: 9, fontWeight: "900" },
  filterChipTextSelected: { color: Colors.inverseText },
  entryList: { gap: 8, marginTop: 10 },
  entryRow: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 64,
    paddingHorizontal: 11,
    paddingVertical: 9,
    ...Effects.controlRaised,
  },
  kindBadge: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: 11,
    borderWidth: 1,
    height: 39,
    justifyContent: "center",
    width: 39,
    ...Effects.recessed,
  },
  kindBadgeFormal: { backgroundColor: Colors.surface3, borderColor: Colors.borderStrong },
  kindBadgeRegional: { backgroundColor: "#282039", borderColor: "#63527C" },
  kindBadgeText: { color: Colors.text, fontSize: 13, fontWeight: "900" },
  entryCopy: { flex: 1 },
  entryTitleRow: { alignItems: "center", flexDirection: "row", gap: 6 },
  entryTerm: { color: Colors.text, fontSize: 14, fontWeight: "900" },
  favoriteStar: { color: Colors.primary, fontSize: 11 },
  entryOfficial: { color: Colors.textMuted, fontSize: 9, marginTop: 3 },
  entryArrow: { color: Colors.textSubtle, fontSize: 22, fontWeight: "900" },
  emptyCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginTop: 10,
    padding: 14,
  },
  emptyIcon: {
    color: Colors.primary,
    fontSize: 29,
    fontWeight: "900",
  },
  emptyCopy: { flex: 1 },
  emptyTitle: { color: Colors.text, fontSize: 12, fontWeight: "900" },
  emptyHint: { color: Colors.textMuted, fontSize: 9, lineHeight: 14, marginTop: 3 },
  communityNote: {
    alignItems: "center",
    backgroundColor: "#171D24",
    borderColor: Colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 11,
    marginTop: 14,
    padding: 13,
  },
  communityIcon: {
    color: Colors.primary,
    fontSize: 24,
    fontWeight: "900",
  },
  communityCopy: { flex: 1 },
  communityTitle: { color: Colors.text, fontSize: 11, fontWeight: "900" },
  communityText: { color: Colors.textMuted, fontSize: 9, lineHeight: 14, marginTop: 3 },
  pressed: { opacity: 0.82, transform: [{ scale: 0.985 }], ...Effects.pressed },

  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: { backgroundColor: "rgba(0,0,0,0.75)", ...StyleSheet.absoluteFill },
  sheet: {
    backgroundColor: Colors.bg,
    borderColor: Colors.borderStrong,
    borderTopLeftRadius: 23,
    borderTopRightRadius: 23,
    borderWidth: 1,
    maxHeight: "88%",
    minHeight: 420,
    paddingBottom: 12,
    paddingHorizontal: 16,
    ...Effects.surfaceRaised,
  },
  sheetHandle: {
    alignSelf: "center",
    backgroundColor: Colors.borderStrong,
    borderRadius: 3,
    height: 4,
    marginBottom: 12,
    marginTop: 8,
    width: 40,
  },
  sheetHeader: { alignItems: "center", flexDirection: "row", gap: 9, marginBottom: 10 },
  sheetHeadingCopy: { flex: 1 },
  sheetEyebrow: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  sheetTitle: { color: Colors.text, fontSize: 27, fontWeight: "900", letterSpacing: -0.3, marginTop: 1 },
  sheetFavorite: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 10,
    height: 39,
    justifyContent: "center",
    width: 39,
    ...Effects.controlRaised,
  },
  sheetFavoriteSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primaryMuted },
  sheetFavoriteText: { color: Colors.textMuted, fontSize: 21, lineHeight: 24 },
  sheetFavoriteTextSelected: { color: Colors.primary },
  doneButton: { backgroundColor: Colors.primary, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 11, ...Effects.primaryRaised },
  doneButtonText: { color: Colors.inverseText, fontSize: 10, fontWeight: "900" },
  sheetContent: { gap: 13, paddingBottom: 24 },
  officialCard: {
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: 13,
    borderWidth: 1,
    padding: 13,
    ...Effects.recessed,
  },
  officialLabel: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  officialValue: { color: Colors.text, fontSize: 16, fontWeight: "900", marginTop: 4 },
  detailBlock: { gap: 6 },
  detailLabel: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.9 },
  detailText: { color: Colors.text, fontSize: 12, lineHeight: 19 },
  aliasWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  aliasChip: { backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: 10, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 7 },
  aliasText: { color: Colors.textMuted, fontSize: 9, fontWeight: "800" },
  regionNote: {
    alignItems: "flex-start",
    backgroundColor: "#282039",
    borderColor: "#63527C",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 11,
  },
  regionIcon: { color: "#B9A4D5", fontSize: 18, fontWeight: "900" },
  noteCopy: { flex: 1 },
  noteTitle: { color: "#C9B8E1", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  noteText: { color: Colors.textMuted, fontSize: 9, lineHeight: 14, marginTop: 3 },
  safetyNote: {
    alignItems: "flex-start",
    backgroundColor: Colors.errorSoft,
    borderColor: "#70413C",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 11,
  },
  safetyIcon: {
    color: Colors.error,
    fontSize: 18,
    fontWeight: "900",
  },
  safetyTitle: { color: "#E3887D", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  languageNote: { color: Colors.textSubtle, fontSize: 8, lineHeight: 13, marginTop: 2 },
});
