import { Layout , Space , Radius, FontSize, Fonts } from "../../theme/tokens";
import { defineStyles } from "../../theme";
import { StyleSheet } from "react-native";

export const useStyles = defineStyles(({ colors: Colors }) => ({
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: Space.sm,
    maxWidth: Layout.contentWidth,
    paddingHorizontal: Space.md,
    paddingVertical: 10,
    width: "100%",
  },

  headerCopy: { flex: 1 },
  headerEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.2 },
  headerTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500" },
  container: {
    alignSelf: "center",
    maxWidth: Layout.contentWidth,
    paddingBottom: 34,
    paddingHorizontal: Space.md,
    width: "100%",
  },
  heroCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.borderStrong,
    borderRadius: Radius.large,
    borderWidth: 1,
    flexDirection: "row",
    gap: Space.sm,
    marginTop: 6,
    overflow: "hidden",
    padding: 14,
    position: "relative",

  },
  heroBolt: {
    alignItems: "center",
    backgroundColor: Colors.action,
    borderRadius: Radius.control,
    height: 46,
    justifyContent: "center",
    transform: [{ rotate: "-4deg" }],
    width: 46,

  },
  heroBoltText: { color: Colors.inverseText, fontSize: FontSize.heading, fontWeight: "500" },
  heroCopy: { flex: 1 },
  heroTitle: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500" },
  heroHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 3 },
  speechMarks: { bottom: -12, opacity: 0.08, position: "absolute", right: 8 },
  speechMarksText: { color: Colors.primary, fontSize: FontSize.hero, fontWeight: "500" },
  searchWrap: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: Space.xs,
    marginTop: 13,
    minHeight: 57,
    paddingHorizontal: Space.sm,

  },
  searchIcon: { color: Colors.primary, fontSize: FontSize.title, fontWeight: "500" },
  searchInput: { color: Colors.text, flex: 1, fontSize: FontSize.label, fontWeight: "500", minHeight: 52, outlineWidth: 0 },
  clearButton: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderRadius: Radius.control,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  clearButtonText: { color: Colors.text, fontSize: FontSize.section, fontWeight: "500", lineHeight: 23 },
  searchSection: { marginTop: 18 },
  sectionRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 20 },
  sectionEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.05 },
  sectionTitle: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500", marginTop: 2 },
  resultCount: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  entryCount: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  dailyCard: {
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.large,
    borderWidth: 1,
    marginTop: 14,
    overflow: "hidden",
    padding: Space.md,

  },
  dailyTopRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  dailyBadge: { backgroundColor: Colors.action, borderRadius: 7, paddingHorizontal: Space.xs, paddingVertical: 5 },
  dailyBadgeText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  dailyArrow: { color: Colors.primary, fontSize: FontSize.subtitle, fontWeight: "500" },
  dailyTerm: { color: Colors.text, fontSize: FontSize.heading, fontWeight: "500", letterSpacing: -0.5, marginTop: Space.sm },
  dailyOfficial: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", marginTop: 2 },
  dailyDefinition: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 15, marginTop: Space.xs },
  quizProgress: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500" },
  quizCard: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.large,
    borderWidth: 1,
    marginTop: 10,
    padding: 14,

  },
  quizPrompt: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500", lineHeight: 20 },
  quizAnswers: { gap: 7, marginTop: Space.sm },
  quizAnswer: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 47,
    paddingHorizontal: 10,

  },
  quizAnswerCorrect: { backgroundColor: Colors.successSoft, borderColor: Colors.success },
  quizAnswerIncorrect: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  answerLetter: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderRadius: Radius.small,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  answerLetterCorrect: { backgroundColor: Colors.success },
  answerLetterIncorrect: { backgroundColor: Colors.error },
  answerLetterText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  quizAnswerText: { color: Colors.text, flex: 1, fontSize: FontSize.caption, fontWeight: "500" },
  answerMark: { color: Colors.success, fontSize: FontSize.body, fontWeight: "500" },
  answerMarkIncorrect: { color: Colors.error, fontSize: FontSize.subtitle, fontWeight: "500" },
  quizFeedback: { alignItems: "center", flexDirection: "row", gap: 10, justifyContent: "space-between", marginTop: 11 },
  quizFeedbackTitle: { color: Colors.textMuted, flex: 1, fontSize: FontSize.caption, fontWeight: "500" },
  nextQuizButton: { backgroundColor: Colors.primarySoft, borderRadius: Radius.small, paddingHorizontal: 10, paddingVertical: Space.xs },
  nextQuizText: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  savedSection: { marginTop: 20 },
  filterRow: { gap: 7, paddingBottom: 3, paddingRight: Space.xs, paddingTop: 10 },
  filterChip: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.large,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 13,

  },
  filterChipSelected: { backgroundColor: Colors.action, borderColor: Colors.primary,  },
  filterChipText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  filterChipTextSelected: { color: Colors.inverseText },
  entryList: { gap: Space.xs, marginTop: 10 },
  entryRow: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 64,
    paddingHorizontal: 11,
    paddingVertical: 9,

  },
  kindBadge: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.control,
    borderWidth: 1,
    height: 39,
    justifyContent: "center",
    width: 39,

  },
  kindBadgeFormal: { backgroundColor: Colors.surface3, borderColor: Colors.borderStrong },
  kindBadgeRegional: { backgroundColor: Colors.primarySoft, borderColor: Colors.primaryMuted },
  kindBadgeText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  entryCopy: { flex: 1 },
  entryTitleRow: { alignItems: "center", flexDirection: "row", gap: 6 },
  entryTerm: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500" },
  favoriteStar: { color: Colors.primary, fontSize: FontSize.caption },
  entryOfficial: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 3 },
  entryArrow: { color: Colors.textSubtle, fontSize: FontSize.section, fontWeight: "500" },
  emptyCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: Space.sm,
    marginTop: 10,
    padding: 14,
  },
  emptyIcon: {
    color: Colors.primary,
    fontSize: FontSize.heading,
    fontWeight: "500",
  },
  emptyCopy: { flex: 1 },
  emptyTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  emptyHint: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 14, marginTop: 3 },
  communityNote: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: 11,
    marginTop: 14,
    padding: 13,
  },
  communityIcon: {
    color: Colors.primary,
    fontSize: FontSize.title,
    fontWeight: "500",
  },
  communityCopy: { flex: 1 },
  communityTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  communityText: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 14, marginTop: 3 },
  pressed: { opacity: 0.82, transform: [{ scale: 0.985 }],  },

  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: { backgroundColor: Colors.overlay, ...StyleSheet.absoluteFill },
  sheet: {
    backgroundColor: Colors.bg,
    borderColor: Colors.borderStrong,
    borderTopLeftRadius: Radius.sheet,
    borderTopRightRadius: Radius.sheet,
    borderWidth: 1,
    maxHeight: "88%",
    minHeight: 420,
    paddingBottom: Space.sm,
    paddingHorizontal: Space.md,

  },
  sheetHandle: {
    alignSelf: "center",
    backgroundColor: Colors.borderStrong,
    borderRadius: 3,
    height: 4,
    marginBottom: Space.sm,
    marginTop: Space.xs,
    width: 40,
  },
  sheetHeader: { alignItems: "center", flexDirection: "row", gap: 9, marginBottom: 10 },
  sheetHeadingCopy: { flex: 1 },
  sheetEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1 },
  sheetTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.heading, fontWeight: "500", letterSpacing: -0.3, marginTop: 1 },
  sheetFavorite: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    height: 39,
    justifyContent: "center",
    width: 39,

  },
  sheetFavoriteSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primaryMuted },
  sheetFavoriteText: { color: Colors.textMuted, fontSize: FontSize.section, lineHeight: 24 },
  sheetFavoriteTextSelected: { color: Colors.primary },
  doneButton: { backgroundColor: Colors.action, borderRadius: Radius.control, paddingHorizontal: Space.sm, paddingVertical: 11,  },
  doneButtonText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500" },
  sheetContent: { gap: 13, paddingBottom: Space.lg },
  officialCard: {
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.control,
    borderWidth: 1,
    padding: 13,

  },
  officialLabel: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1 },
  officialValue: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500", marginTop: Space.xxs },
  detailBlock: { gap: 6 },
  detailLabel: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.9 },
  detailText: { color: Colors.text, fontSize: FontSize.caption, lineHeight: 19 },
  aliasWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  aliasChip: { backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 7 },
  aliasText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  regionNote: {
    alignItems: "flex-start",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 11,
  },
  regionIcon: { color: Colors.primary, fontSize: FontSize.subtitle, fontWeight: "500" },
  noteCopy: { flex: 1 },
  noteTitle: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  noteText: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 14, marginTop: 3 },
  safetyNote: {
    alignItems: "flex-start",
    backgroundColor: Colors.errorSoft,
    borderColor: Colors.error,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 11,
  },
  safetyIcon: {
    color: Colors.error,
    fontSize: FontSize.subtitle,
    fontWeight: "500",
  },
  safetyTitle: { color: Colors.error, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  languageNote: { color: Colors.textSubtle, fontSize: FontSize.caption, lineHeight: 13, marginTop: 2 },
}));
