import { Layout , Space , FontSize, Radius, Fonts } from "../../theme/tokens";
import { defineStyles } from "../../theme";
import { StyleSheet } from "react-native";

export const useStyles = defineStyles(({ colors: Colors }) => ({
  boardStatus: { alignSelf: "center", maxWidth: 528, width: "94%" },
  errorText: { color: Colors.error, fontSize: FontSize.caption, lineHeight: 19, paddingVertical: Space.xs },
  quantityInput: { color: Colors.text, backgroundColor: Colors.surface, borderColor: Colors.border, borderWidth: 1, borderRadius: Radius.control, width: 64, minHeight: 44, paddingHorizontal: 10, fontSize: FontSize.body },
  completedLink: { minHeight: 44, justifyContent: "center", alignSelf: "flex-start", paddingVertical: Space.sm, marginTop: Space.xs },
  completedLinkText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "600" },
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: { alignItems: "center", alignSelf: "center", flexDirection: "row", gap: 11, maxWidth: Layout.contentWidth, paddingHorizontal: Space.md, paddingVertical: 10, width: "100%" },

  headerCopy: { flex: 1 },
  headerEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.2 },
  headerTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500" },
  openBadge: { alignItems: "center", backgroundColor: Colors.primarySoft, borderColor: Colors.primaryMuted, borderRadius: Radius.control, borderWidth: 1, minWidth: 43, paddingHorizontal: 7, paddingVertical: 5,  },
  openBadgeNumber: { color: Colors.primary, fontSize: FontSize.label, fontWeight: "500", lineHeight: 16 },
  openBadgeLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  tabBar: { alignSelf: "center", backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, flexDirection: "row", gap: 3, maxWidth: 528, padding: Space.xxs, width: "94%",  },
  tab: { alignItems: "center", borderRadius: Radius.small, flex: 1, justifyContent: "center", minHeight: 38 },
  tabSelected: { backgroundColor: Colors.surface3,  },
  tabText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  tabTextSelected: { color: Colors.text },
  container: { alignSelf: "center", maxWidth: Layout.contentWidth, paddingBottom: 34, paddingHorizontal: Space.md, paddingTop: Space.sm, width: "100%" },
  quickCard: { backgroundColor: Colors.surface, borderColor: Colors.borderStrong, borderRadius: Radius.large, borderWidth: 1, padding: 13,  },
  quickEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.1, marginBottom: 9 },
  kindRow: { flexDirection: "row", gap: 6, marginTop: Space.xs },
  kindChip: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, flex: 1, flexDirection: "row", gap: 5, justifyContent: "center", minHeight: 38, paddingHorizontal: Space.xxs },
  kindChipSelected: { backgroundColor: Colors.action, borderColor: Colors.primary,  },
  kindIcon: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  kindText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  kindTextSelected: { color: Colors.inverseText },
  quickInputRow: { flexDirection: "row", gap: Space.xs, marginTop: 9 },
  quickInput: { backgroundColor: Colors.surface2, borderColor: Colors.primaryMuted, borderRadius: Radius.control, borderWidth: 1, color: Colors.text, flex: 1, fontSize: FontSize.label, fontWeight: "500", minHeight: 51, outlineWidth: 0, paddingHorizontal: 13 },
  addButton: { alignItems: "center", backgroundColor: Colors.action, borderColor: Colors.primary, borderRadius: Radius.control, borderWidth: 1, justifyContent: "center", width: 52,  },
  addButtonDisabled: { opacity: 0.35 },
  addButtonText: { color: Colors.inverseText, fontSize: FontSize.label, fontWeight: "500" },
  quickHint: { color: Colors.textSubtle, fontSize: FontSize.caption, lineHeight: 12, marginTop: Space.xs },
  sectionRow: { alignItems: "flex-end", flexDirection: "row", justifyContent: "space-between", marginTop: 19 },
  sectionTitle: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500" },
  sectionHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  sectionCount: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  itemList: { gap: Space.xs, marginTop: 10 },
  itemCard: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.card, borderWidth: 1, flexDirection: "row", gap: 9, minHeight: 72, paddingHorizontal: 10, paddingVertical: 9,  },
  itemCardHigh: { borderLeftColor: Colors.primary, borderLeftWidth: 3 },
  checkButton: { alignItems: "center", backgroundColor: Colors.surface2, borderColor: Colors.borderStrong, borderRadius: Radius.small, borderWidth: 1, height: 34, justifyContent: "center", width: 34,  },
  checkButtonDone: { backgroundColor: Colors.action, borderColor: Colors.primary },
  checkButtonText: { color: Colors.inverseText, fontSize: FontSize.body, fontWeight: "500" },
  itemMain: { flex: 1, gap: 5, minWidth: 0 },
  itemTitleRow: { alignItems: "center", flexDirection: "row", gap: 7 },
  itemKindBadge: { alignItems: "center", backgroundColor: Colors.primarySoft, borderRadius: 7, height: 23, justifyContent: "center", width: 23 },
  itemKindIcon: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  itemTitle: { color: Colors.text, flex: 1, fontSize: FontSize.label, fontWeight: "500", lineHeight: 21 },
  itemTitleDone: { color: Colors.textSubtle, textDecorationLine: "line-through" },
  itemBottomRow: { alignItems: "center", flexDirection: "row", gap: 6 },
  itemMeta: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 17 },
  detailCount: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.5 },
  quantityPill: { backgroundColor: Colors.surface3, borderRadius: 7, color: Colors.text, fontSize: FontSize.caption, fontWeight: "500", paddingHorizontal: 6, paddingVertical: Space.xxs },
  arrowButton: { alignItems: "center", height: 40, justifyContent: "center", width: 25 },
  itemArrow: { color: Colors.textSubtle, fontSize: FontSize.title, fontWeight: "500" },
  emptyCard: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.card, borderStyle: "dashed", borderWidth: 1, marginTop: 11, padding: 23 },
  emptyIcon: { color: Colors.primary, fontSize: FontSize.heading, fontWeight: "500" },
  emptyTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500", marginTop: 6, textAlign: "center" },
  emptyHint: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 14, marginTop: Space.xxs, textAlign: "center" },
  doneHero: { alignItems: "center", backgroundColor: Colors.successSoft, borderColor: Colors.success, borderRadius: Radius.card, borderWidth: 1, flexDirection: "row", gap: 13, padding: 15,  },
  doneNumber: { color: Colors.success, fontSize: FontSize.screen, fontWeight: "500" },
  doneCopy: { flex: 1 },
  materialHero: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.borderStrong, borderRadius: Radius.large, borderWidth: 1, flexDirection: "row", gap: 14, padding: 15,  },
  materialRing: { alignItems: "center", backgroundColor: Colors.primarySoft, borderColor: Colors.primary, borderRadius: Radius.pill, borderWidth: 2, height: 58, justifyContent: "center", width: 58,  },
  materialNumber: { color: Colors.primary, fontSize: FontSize.section, fontWeight: "500", lineHeight: 22 },
  materialRingLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.5 },
  materialHeroCopy: { flex: 1 },
  materialList: { gap: Space.xs, marginTop: Space.sm },
  materialRow: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, flexDirection: "row", gap: 10, minHeight: 65, padding: 10,  },
  materialRowMain: { flex: 1 },
  materialName: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  materialSource: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 12, marginTop: 3 },
  jobCreateCard: { backgroundColor: Colors.surface, borderColor: Colors.borderStrong, borderRadius: Radius.card, borderWidth: 1, padding: 14,  },
  jobCreateCopy: { marginBottom: 11 },
  jobInputRow: { flexDirection: "row", gap: 7 },
  jobInput: { backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, color: Colors.text, flex: 1, fontSize: FontSize.caption, minHeight: 45, outlineWidth: 0, paddingHorizontal: 11 },
  jobAddButton: { alignItems: "center", backgroundColor: Colors.action, borderRadius: Radius.control, justifyContent: "center", paddingHorizontal: 13,  },
  jobAddText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500" },
  jobList: { gap: Space.xs, marginTop: 11 },
  jobCard: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.card, borderWidth: 1, flexDirection: "row", gap: 10, minHeight: 67, padding: 10,  },
  jobCardSelected: { borderColor: Colors.primaryMuted, borderBottomLeftRadius: 5, borderBottomRightRadius: 5 },
  jobMark: { alignItems: "center", backgroundColor: Colors.primarySoft, borderColor: Colors.primaryMuted, borderRadius: Radius.control, borderWidth: 1, height: 40, justifyContent: "center", width: 40 },
  jobMarkText: { color: Colors.primary, fontSize: FontSize.body, fontWeight: "500" },
  jobCardCopy: { flex: 1 },
  jobName: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500" },
  jobMeta: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 3 },
  jobExpanded: { backgroundColor: Colors.surface, borderBottomLeftRadius: 14, borderBottomRightRadius: 14, borderColor: Colors.primaryMuted, borderTopWidth: 0, borderWidth: 1, padding: 9 },
  removeJobButton: { alignItems: "center", padding: 11 },
  removeJobText: { color: Colors.error, fontSize: FontSize.caption, fontWeight: "500" },
  toast: { alignItems: "center", alignSelf: "center", backgroundColor: Colors.successSoft, borderColor: Colors.success, borderRadius: Radius.control, borderWidth: 1, bottom: 22, flexDirection: "row", gap: Space.xs, maxWidth: 400, paddingHorizontal: 13, paddingVertical: 10, position: "absolute",  },
  toastCheck: { color: Colors.success, fontSize: FontSize.label, fontWeight: "500" },
  toastText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  pressed: { opacity: 0.82, transform: [{ scale: 0.985 }],  },
  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: { backgroundColor: Colors.overlay, ...StyleSheet.absoluteFill },
  sheet: { backgroundColor: Colors.bg, borderColor: Colors.borderStrong, borderTopLeftRadius: Radius.sheet, borderTopRightRadius: Radius.sheet, borderWidth: 1, maxHeight: "91%", minHeight: 470, paddingBottom: 10, paddingHorizontal: Space.md,  },
  sheetHandle: { alignSelf: "center", backgroundColor: Colors.borderStrong, borderRadius: 2, height: 4, marginTop: Space.xs, width: 42 },
  sheetHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingVertical: 11 },
  sheetEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1 },
  sheetTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.subtitle, fontWeight: "500" },
  doneButton: { backgroundColor: Colors.action, borderRadius: Radius.control, minWidth: 69, paddingHorizontal: 14, paddingVertical: 10,  },
  doneButtonText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500", textAlign: "center" },
  titleInput: { backgroundColor: Colors.surface2, borderColor: Colors.primaryMuted, borderRadius: Radius.control, borderWidth: 1, color: Colors.text, fontSize: FontSize.body, fontWeight: "500", minHeight: 65, outlineWidth: 0, padding: Space.sm },
  fieldLabel: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.9, marginBottom: 6, marginTop: 14 },
  jobChipRow: { flexDirection: "row", gap: 6, paddingRight: 10 },
  choiceChip: { backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, minHeight: 39, paddingHorizontal: Space.sm, paddingVertical: 11 },
  choiceChipSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  choiceText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  choiceTextSelected: { color: Colors.text },
  detailsToggle: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.borderStrong, borderRadius: Radius.control, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: Space.md, padding: 13,  },
  detailsToggleTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  detailsToggleHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  detailsToggleArrow: { color: Colors.primary, fontSize: FontSize.section, fontWeight: "500" },
  detailsWrap: { paddingBottom: Space.xxs },
  fieldInput: { backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, color: Colors.text, fontSize: FontSize.caption, minHeight: 45, outlineWidth: 0, paddingHorizontal: 11 },
  notesInput: { minHeight: 80, paddingTop: 11 },
  choiceRow: { flexDirection: "row", gap: 6 },
  choiceButton: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, flex: 1, justifyContent: "center", minHeight: 40 },
  choiceButtonSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  choiceButtonText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  materialQuantityCard: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 14, padding: 10 },
  quantityValue: { color: Colors.text, fontSize: FontSize.section, fontWeight: "500" },
  quantityUnit: { color: Colors.textMuted, fontSize: FontSize.caption },
  stepper: { flexDirection: "row", gap: 6 },
  stepperButton: { alignItems: "center", backgroundColor: Colors.surface3, borderColor: Colors.borderStrong, borderRadius: Radius.control, borderWidth: 1, height: 40, justifyContent: "center", width: 46,  },
  stepperText: { color: Colors.text, fontSize: FontSize.subtitle, fontWeight: "500" },
  subLine: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, flexDirection: "row", gap: 9, marginBottom: 6, minHeight: 43, paddingHorizontal: 9 },
  smallCheck: { alignItems: "center", borderColor: Colors.borderStrong, borderRadius: 6, borderWidth: 1, height: 23, justifyContent: "center", width: 23 },
  smallCheckDone: { backgroundColor: Colors.action, borderColor: Colors.primary },
  smallCheckText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500" },
  subLineText: { color: Colors.text, flex: 1, fontSize: FontSize.caption, fontWeight: "500" },
  subLineTextDone: { color: Colors.textSubtle, textDecorationLine: "line-through" },
  inlineAdd: { flexDirection: "row", gap: 6 },
  inlineAddInput: { backgroundColor: Colors.surface2, borderColor: Colors.border, borderRadius: Radius.control, borderWidth: 1, color: Colors.text, flex: 1, fontSize: FontSize.caption, minHeight: 43, outlineWidth: 0, paddingHorizontal: 10 },
  inlineAddButton: { alignItems: "center", backgroundColor: Colors.surface3, borderColor: Colors.borderStrong, borderRadius: Radius.control, borderWidth: 1, justifyContent: "center", paddingHorizontal: 10 },
  inlineAddText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  deleteButton: { alignItems: "center", borderColor: Colors.error, borderRadius: Radius.control, borderWidth: 1, marginBottom: 14, marginTop: 21, padding: Space.sm },
  deleteButtonText: { color: Colors.error, fontSize: FontSize.caption, fontWeight: "500" },
}));
