import { StyleSheet } from "react-native";

import { Colors, Effects } from "../../theme";

export const styles = StyleSheet.create({
  boardStatus: { alignSelf: "center", maxWidth: 528, width: "94%" },
  errorText: { color: Colors.error, fontSize: 13, lineHeight: 19, paddingVertical: 8 },
  quantityInput: { color: Colors.text, backgroundColor: Colors.surface, borderColor: Colors.border, borderWidth: 1, borderRadius: 10, width: 64, minHeight: 44, paddingHorizontal: 10, fontSize: 16 },
  completedLink: { minHeight: 44, justifyContent: "center", alignSelf: "flex-start", paddingVertical: 12, marginTop: 8 },
  completedLinkText: { color: Colors.textMuted, fontSize: 13, fontWeight: "600" },
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: { alignItems: "center", alignSelf: "center", flexDirection: "row", gap: 11, maxWidth: 560, paddingHorizontal: 16, paddingVertical: 10, width: "100%" },
  homeButton: { backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 12, borderWidth: 1, paddingHorizontal: 13, paddingVertical: 10, ...Effects.controlRaised },
  homeButtonText: { color: Colors.text, fontSize: 13, fontWeight: "800" },
  headerCopy: { flex: 1 },
  headerEyebrow: { color: Colors.primary, fontSize: 9, fontWeight: "900", letterSpacing: 1.2 },
  headerTitle: { color: Colors.text, fontSize: 20, fontWeight: "900" },
  openBadge: { alignItems: "center", backgroundColor: Colors.primarySoft, borderColor: Colors.primaryMuted, borderRadius: 11, borderWidth: 1, minWidth: 43, paddingHorizontal: 7, paddingVertical: 5, ...Effects.recessed },
  openBadgeNumber: { color: Colors.primary, fontSize: 15, fontWeight: "900", lineHeight: 16 },
  openBadgeLabel: { color: Colors.textMuted, fontSize: 6, fontWeight: "900", letterSpacing: 0.8 },
  tabBar: { alignSelf: "center", backgroundColor: "#0E1216", borderColor: Colors.border, borderRadius: 13, borderWidth: 1, flexDirection: "row", gap: 3, maxWidth: 528, padding: 4, width: "94%", ...Effects.recessed },
  tab: { alignItems: "center", borderRadius: 9, flex: 1, justifyContent: "center", minHeight: 38 },
  tabSelected: { backgroundColor: Colors.surface3, ...Effects.controlRaised },
  tabText: { color: Colors.textMuted, fontSize: 13, fontWeight: "700" },
  tabTextSelected: { color: Colors.text },
  container: { alignSelf: "center", maxWidth: 560, paddingBottom: 34, paddingHorizontal: 16, paddingTop: 12, width: "100%" },
  quickCard: { backgroundColor: "#181F28", borderColor: Colors.borderStrong, borderRadius: 18, borderWidth: 1, padding: 13, ...Effects.surfaceRaised },
  quickEyebrow: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1.1, marginBottom: 9 },
  kindRow: { flexDirection: "row", gap: 6, marginTop: 8 },
  kindChip: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 10, borderWidth: 1, flex: 1, flexDirection: "row", gap: 5, justifyContent: "center", minHeight: 38, paddingHorizontal: 4 },
  kindChipSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary, ...Effects.primaryRaised },
  kindIcon: { color: Colors.textMuted, fontSize: 12, fontWeight: "900" },
  kindText: { color: Colors.textMuted, fontSize: 9, fontWeight: "900" },
  kindTextSelected: { color: Colors.inverseText },
  quickInputRow: { flexDirection: "row", gap: 8, marginTop: 9 },
  quickInput: { backgroundColor: "#0E1318", borderColor: Colors.primaryMuted, borderRadius: 13, borderWidth: 1, color: Colors.text, flex: 1, fontSize: 14, fontWeight: "700", minHeight: 51, outlineWidth: 0, paddingHorizontal: 13 },
  addButton: { alignItems: "center", backgroundColor: Colors.primary, borderColor: Colors.primary, borderRadius: 13, borderWidth: 1, justifyContent: "center", width: 52, ...Effects.primaryRaised },
  addButtonDisabled: { opacity: 0.35 },
  addButtonText: { color: Colors.inverseText, fontSize: 15, fontWeight: "800" },
  quickHint: { color: Colors.textSubtle, fontSize: 8, lineHeight: 12, marginTop: 8 },
  sectionRow: { alignItems: "flex-end", flexDirection: "row", justifyContent: "space-between", marginTop: 19 },
  sectionTitle: { color: Colors.text, fontSize: 17, fontWeight: "900" },
  sectionHint: { color: Colors.textMuted, fontSize: 9, marginTop: 2 },
  sectionCount: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  itemList: { gap: 8, marginTop: 10 },
  itemCard: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 9, minHeight: 72, paddingHorizontal: 10, paddingVertical: 9, ...Effects.controlRaised },
  itemCardHigh: { borderLeftColor: Colors.primary, borderLeftWidth: 3 },
  checkButton: { alignItems: "center", backgroundColor: "#11171D", borderColor: Colors.borderStrong, borderRadius: 9, borderWidth: 1, height: 34, justifyContent: "center", width: 34, ...Effects.recessed },
  checkButtonDone: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  checkButtonText: { color: Colors.inverseText, fontSize: 17, fontWeight: "900" },
  itemMain: { flex: 1, gap: 5, minWidth: 0 },
  itemTitleRow: { alignItems: "center", flexDirection: "row", gap: 7 },
  itemKindBadge: { alignItems: "center", backgroundColor: Colors.primarySoft, borderRadius: 7, height: 23, justifyContent: "center", width: 23 },
  itemKindIcon: { color: Colors.primary, fontSize: 10, fontWeight: "900" },
  itemTitle: { color: Colors.text, flex: 1, fontSize: 15, fontWeight: "700", lineHeight: 21 },
  itemTitleDone: { color: Colors.textSubtle, textDecorationLine: "line-through" },
  itemBottomRow: { alignItems: "center", flexDirection: "row", gap: 6 },
  itemMeta: { color: Colors.textMuted, fontSize: 12, lineHeight: 17 },
  detailCount: { color: Colors.primary, fontSize: 6, fontWeight: "900", letterSpacing: 0.5 },
  quantityPill: { backgroundColor: Colors.surface3, borderRadius: 7, color: Colors.text, fontSize: 8, fontWeight: "900", paddingHorizontal: 6, paddingVertical: 4 },
  arrowButton: { alignItems: "center", height: 40, justifyContent: "center", width: 25 },
  itemArrow: { color: Colors.textSubtle, fontSize: 23, fontWeight: "900" },
  emptyCard: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 16, borderStyle: "dashed", borderWidth: 1, marginTop: 11, padding: 23 },
  emptyIcon: { color: Colors.primary, fontSize: 27, fontWeight: "900" },
  emptyTitle: { color: Colors.text, fontSize: 13, fontWeight: "900", marginTop: 6, textAlign: "center" },
  emptyHint: { color: Colors.textMuted, fontSize: 9, lineHeight: 14, marginTop: 4, textAlign: "center" },
  doneHero: { alignItems: "center", backgroundColor: "#19231F", borderColor: "#3E6A56", borderRadius: 17, borderWidth: 1, flexDirection: "row", gap: 13, padding: 15, ...Effects.surfaceRaised },
  doneNumber: { color: "#72C69B", fontSize: 34, fontWeight: "900" },
  doneCopy: { flex: 1 },
  materialHero: { alignItems: "center", backgroundColor: "#181F28", borderColor: Colors.borderStrong, borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 14, padding: 15, ...Effects.surfaceRaised },
  materialRing: { alignItems: "center", backgroundColor: Colors.primarySoft, borderColor: Colors.primary, borderRadius: 29, borderWidth: 2, height: 58, justifyContent: "center", width: 58, ...Effects.recessed },
  materialNumber: { color: Colors.primary, fontSize: 21, fontWeight: "900", lineHeight: 22 },
  materialRingLabel: { color: Colors.textMuted, fontSize: 6, fontWeight: "900", letterSpacing: 0.5 },
  materialHeroCopy: { flex: 1 },
  materialList: { gap: 8, marginTop: 12 },
  materialRow: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 13, borderWidth: 1, flexDirection: "row", gap: 10, minHeight: 65, padding: 10, ...Effects.controlRaised },
  materialRowMain: { flex: 1 },
  materialName: { color: Colors.text, fontSize: 13, fontWeight: "900" },
  materialSource: { color: Colors.textMuted, fontSize: 8, lineHeight: 12, marginTop: 3 },
  jobCreateCard: { backgroundColor: "#181F28", borderColor: Colors.borderStrong, borderRadius: 17, borderWidth: 1, padding: 14, ...Effects.surfaceRaised },
  jobCreateCopy: { marginBottom: 11 },
  jobInputRow: { flexDirection: "row", gap: 7 },
  jobInput: { backgroundColor: "#0E1318", borderColor: Colors.border, borderRadius: 11, borderWidth: 1, color: Colors.text, flex: 1, fontSize: 12, minHeight: 45, outlineWidth: 0, paddingHorizontal: 11 },
  jobAddButton: { alignItems: "center", backgroundColor: Colors.primary, borderRadius: 11, justifyContent: "center", paddingHorizontal: 13, ...Effects.primaryRaised },
  jobAddText: { color: Colors.inverseText, fontSize: 10, fontWeight: "900" },
  jobList: { gap: 8, marginTop: 11 },
  jobCard: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 10, minHeight: 67, padding: 10, ...Effects.controlRaised },
  jobCardSelected: { borderColor: Colors.primaryMuted, borderBottomLeftRadius: 5, borderBottomRightRadius: 5 },
  jobMark: { alignItems: "center", backgroundColor: Colors.primarySoft, borderColor: Colors.primaryMuted, borderRadius: 10, borderWidth: 1, height: 40, justifyContent: "center", width: 40 },
  jobMarkText: { color: Colors.primary, fontSize: 16, fontWeight: "900" },
  jobCardCopy: { flex: 1 },
  jobName: { color: Colors.text, fontSize: 14, fontWeight: "900" },
  jobMeta: { color: Colors.textMuted, fontSize: 9, marginTop: 3 },
  jobExpanded: { backgroundColor: "#141A21", borderBottomLeftRadius: 14, borderBottomRightRadius: 14, borderColor: Colors.primaryMuted, borderTopWidth: 0, borderWidth: 1, padding: 9 },
  removeJobButton: { alignItems: "center", padding: 11 },
  removeJobText: { color: Colors.error, fontSize: 9, fontWeight: "900" },
  toast: { alignItems: "center", alignSelf: "center", backgroundColor: "#26342D", borderColor: "#4C8A6C", borderRadius: 12, borderWidth: 1, bottom: 22, flexDirection: "row", gap: 8, maxWidth: 400, paddingHorizontal: 13, paddingVertical: 10, position: "absolute", ...Effects.surfaceRaised },
  toastCheck: { color: "#72C69B", fontSize: 14, fontWeight: "900" },
  toastText: { color: Colors.text, fontSize: 10, fontWeight: "800" },
  pressed: { opacity: 0.82, transform: [{ scale: 0.985 }], ...Effects.pressed },
  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: { backgroundColor: "rgba(0,0,0,0.78)", ...StyleSheet.absoluteFill },
  sheet: { backgroundColor: Colors.bg, borderColor: Colors.borderStrong, borderTopLeftRadius: 23, borderTopRightRadius: 23, borderWidth: 1, maxHeight: "91%", minHeight: 470, paddingBottom: 10, paddingHorizontal: 16, ...Effects.surfaceRaised },
  sheetHandle: { alignSelf: "center", backgroundColor: Colors.borderStrong, borderRadius: 2, height: 4, marginTop: 8, width: 42 },
  sheetHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingVertical: 11 },
  sheetEyebrow: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  sheetTitle: { color: Colors.text, fontSize: 19, fontWeight: "900" },
  doneButton: { backgroundColor: Colors.primary, borderRadius: 10, minWidth: 69, paddingHorizontal: 14, paddingVertical: 10, ...Effects.primaryRaised },
  doneButtonText: { color: Colors.inverseText, fontSize: 11, fontWeight: "900", textAlign: "center" },
  titleInput: { backgroundColor: "#0E1318", borderColor: Colors.primaryMuted, borderRadius: 13, borderWidth: 1, color: Colors.text, fontSize: 16, fontWeight: "900", minHeight: 65, outlineWidth: 0, padding: 12 },
  fieldLabel: { color: Colors.textSubtle, fontSize: 7, fontWeight: "900", letterSpacing: 0.9, marginBottom: 6, marginTop: 14 },
  jobChipRow: { flexDirection: "row", gap: 6, paddingRight: 10 },
  choiceChip: { backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 10, borderWidth: 1, minHeight: 39, paddingHorizontal: 12, paddingVertical: 11 },
  choiceChipSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  choiceText: { color: Colors.textMuted, fontSize: 9, fontWeight: "900" },
  choiceTextSelected: { color: Colors.text },
  detailsToggle: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.borderStrong, borderRadius: 13, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 16, padding: 13, ...Effects.controlRaised },
  detailsToggleTitle: { color: Colors.text, fontSize: 12, fontWeight: "900" },
  detailsToggleHint: { color: Colors.textMuted, fontSize: 8, marginTop: 2 },
  detailsToggleArrow: { color: Colors.primary, fontSize: 20, fontWeight: "900" },
  detailsWrap: { paddingBottom: 4 },
  fieldInput: { backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 11, borderWidth: 1, color: Colors.text, fontSize: 11, minHeight: 45, outlineWidth: 0, paddingHorizontal: 11 },
  notesInput: { minHeight: 80, paddingTop: 11 },
  choiceRow: { flexDirection: "row", gap: 6 },
  choiceButton: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 10, borderWidth: 1, flex: 1, justifyContent: "center", minHeight: 40 },
  choiceButtonSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  choiceButtonText: { color: Colors.textMuted, fontSize: 9, fontWeight: "900" },
  materialQuantityCard: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 12, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 14, padding: 10 },
  quantityValue: { color: Colors.text, fontSize: 20, fontWeight: "900" },
  quantityUnit: { color: Colors.textMuted, fontSize: 10 },
  stepper: { flexDirection: "row", gap: 6 },
  stepperButton: { alignItems: "center", backgroundColor: Colors.surface3, borderColor: Colors.borderStrong, borderRadius: 10, borderWidth: 1, height: 40, justifyContent: "center", width: 46, ...Effects.controlRaised },
  stepperText: { color: Colors.text, fontSize: 19, fontWeight: "900" },
  subLine: { alignItems: "center", backgroundColor: Colors.surface, borderColor: Colors.border, borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 9, marginBottom: 6, minHeight: 43, paddingHorizontal: 9 },
  smallCheck: { alignItems: "center", borderColor: Colors.borderStrong, borderRadius: 6, borderWidth: 1, height: 23, justifyContent: "center", width: 23 },
  smallCheckDone: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  smallCheckText: { color: Colors.inverseText, fontSize: 11, fontWeight: "900" },
  subLineText: { color: Colors.text, flex: 1, fontSize: 10, fontWeight: "700" },
  subLineTextDone: { color: Colors.textSubtle, textDecorationLine: "line-through" },
  inlineAdd: { flexDirection: "row", gap: 6 },
  inlineAddInput: { backgroundColor: "#0E1318", borderColor: Colors.border, borderRadius: 10, borderWidth: 1, color: Colors.text, flex: 1, fontSize: 10, minHeight: 43, outlineWidth: 0, paddingHorizontal: 10 },
  inlineAddButton: { alignItems: "center", backgroundColor: Colors.surface3, borderColor: Colors.borderStrong, borderRadius: 10, borderWidth: 1, justifyContent: "center", paddingHorizontal: 10 },
  inlineAddText: { color: Colors.text, fontSize: 8, fontWeight: "900" },
  deleteButton: { alignItems: "center", borderColor: "#633933", borderRadius: 11, borderWidth: 1, marginBottom: 14, marginTop: 21, padding: 12 },
  deleteButtonText: { color: Colors.error, fontSize: 9, fontWeight: "900" },
});
