import { Layout , Space , Radius, FontSize, Fonts } from "../../theme/tokens";
import { defineStyles } from "../../theme";
import { StyleSheet } from "react-native";

export const useStyles = defineStyles(({ colors: Colors }) => ({
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: Space.sm,
    maxWidth: Layout.contentWidth,
    paddingHorizontal: Space.md,
    paddingVertical: 10,
    width: "100%",
  },

  headerCopy: { flex: 1 },
  headerEyebrow: {
    color: Colors.primary,
    fontSize: FontSize.caption,
    fontWeight: "500",
    letterSpacing: 1.2,
  },
  headerTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500" },
  modeSwitchWrap: {
    alignSelf: "center",
    maxWidth: Layout.contentWidth,
    paddingHorizontal: Space.md,
    paddingTop: Space.xxs,
    width: "100%",
  },
  container: {
    alignSelf: "center",
    maxWidth: Layout.contentWidth,
    paddingBottom: 30,
    paddingHorizontal: Space.md,
    width: "100%",
  },
  introRow: { alignItems: "center", flexDirection: "row", gap: 11, marginTop: 18 },
  stepBadge: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.control,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,

  },
  stepBadgeText: { color: Colors.primary, fontSize: FontSize.label, fontWeight: "500" },
  stepCopy: { flex: 1 },
  sectionTitle: { color: Colors.text, fontSize: FontSize.subtitle, fontWeight: "500" },
  sectionHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  choiceRow: { flexDirection: "row", gap: Space.xs, marginTop: Space.sm },
  choice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 7,

  },
  choiceSelected: { backgroundColor: Colors.action, borderColor: Colors.primary },
  choiceText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", textAlign: "center" },
  choiceTextSelected: { color: Colors.inverseText },
  sizeChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,

  },
  sizeChoiceText: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500" },
  expandedChoices: { flexDirection: "row", flexWrap: "wrap", gap: Space.xs, marginTop: Space.xs },
  expandedChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    minHeight: 42,
    minWidth: 120,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  smallExpandedChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    minHeight: 42,
    minWidth: 66,
    paddingHorizontal: 11,
    justifyContent: "center",
  },
  expandedChoiceSelected: { borderColor: Colors.primary, backgroundColor: Colors.primarySoft },
  expandedChoiceText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  divider: { backgroundColor: Colors.border, height: StyleSheet.hairlineWidth, marginTop: 20 },
  wireList: { gap: 9, marginTop: Space.sm },
  wireRow: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: Space.xs,
    minHeight: 70,
    padding: Space.xs,

  },
  wireSizeButton: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 50,
    paddingHorizontal: Space.sm,
  },
  wireSizeLabel: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.7 },
  wireSizeValue: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500", marginTop: 2 },
  chevron: { color: Colors.textMuted, fontSize: FontSize.body, fontWeight: "500" },
  removeButton: {
    alignItems: "center",
    backgroundColor: Colors.errorSoft,
    borderRadius: Radius.control,
    height: 42,
    justifyContent: "center",
    width: 34,
  },
  removeButtonText: { color: Colors.error, fontSize: FontSize.section, fontWeight: "500", lineHeight: 23 },
  addWireButton: {
    alignItems: "center",
    borderColor: Colors.borderStrong,
    borderRadius: Radius.control,
    borderStyle: "dashed",
    borderWidth: 1,
    flexDirection: "row",
    gap: Space.xs,
    justifyContent: "center",
    marginTop: 10,
    minHeight: 48,
  },
  addWireIcon: { color: Colors.primary, fontSize: FontSize.subtitle, fontWeight: "500" },
  addWireText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  resultCard: {
    backgroundColor: Colors.successSoft,
    borderColor: Colors.success,
    borderRadius: Radius.large,
    borderWidth: 1,
    marginTop: 22,
    padding: 17,

  },
  resultCardFail: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  resultTopRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  resultEyebrow: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.1 },
  resultStatus: { color: Colors.success, fontSize: FontSize.screen, fontWeight: "500", letterSpacing: 0.4 },
  resultStatusFail: { color: Colors.error },
  fillBadge: {
    alignItems: "center",
    backgroundColor: Colors.successSoft,
    borderColor: Colors.success,
    borderRadius: Radius.control,
    borderWidth: 1,
    minWidth: 74,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  fillBadgeFail: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  fillBadgeValue: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500" },
  fillBadgeLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.7 },
  meterTrack: {
    backgroundColor: Colors.bg,
    borderRadius: 7,
    height: 12,
    marginTop: Space.md,
    overflow: "hidden",
    position: "relative",
  },
  meterFill: { backgroundColor: Colors.success, borderRadius: 7, height: "100%" },
  meterFillFail: { backgroundColor: Colors.error },
  meterLimit: { backgroundColor: Colors.action, height: "100%", position: "absolute", width: 2, zIndex: 2 },
  meterLabels: { flexDirection: "row", justifyContent: "space-between", marginTop: 6 },
  meterLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  resultDetails: {
    borderTopColor: Colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    marginTop: 15,
    paddingTop: 14,
  },
  detailBlock: { flex: 1 },
  detailRule: { backgroundColor: Colors.border, marginHorizontal: Space.sm, width: 1 },
  detailLabel: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  detailValue: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500", marginTop: 3 },
  codeNote: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    marginTop: Space.sm,
    padding: 13,
  },
  codeNoteTitle: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.8 },
  codeNoteText: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 16, marginTop: Space.xxs },
  pressed: { opacity: 0.78, transform: [{ scale: 0.98 }],  },
  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: {
    backgroundColor: Colors.overlay,
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  sheet: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderTopLeftRadius: Radius.sheet,
    borderTopRightRadius: Radius.sheet,
    borderWidth: 1,
    maxHeight: "78%",
    paddingBottom: 10,
  },
  sheetHandle: { alignSelf: "center", backgroundColor: Colors.borderStrong, borderRadius: 3, height: 4, marginTop: 9, width: 42 },
  sheetHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", padding: Space.md },
  sheetEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1 },
  sheetTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500", marginTop: 2 },
  doneButton: { backgroundColor: Colors.action, borderRadius: Radius.control, paddingHorizontal: 14, paddingVertical: 9 },
  doneButtonText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500" },
  wireSizeGrid: { flexDirection: "row", flexWrap: "wrap", gap: Space.xs, paddingBottom: 18, paddingHorizontal: Space.md },
  wireSizeOption: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 48,
    width: "30.8%",
  },
  wireSizeOptionSelected: { backgroundColor: Colors.action, borderColor: Colors.primary },
  wireSizeOptionText: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500" },
  wireSizeOptionTextSelected: { color: Colors.inverseText },
}));
