import { StyleSheet } from "react-native";

import { Colors, Effects } from "../../theme";

export const styles = StyleSheet.create({
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: 12,
    maxWidth: 560,
    paddingHorizontal: 16,
    paddingVertical: 10,
    width: "100%",
  },
  homeButton: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 10,
    ...Effects.controlRaised,
  },
  homeButtonText: { color: Colors.text, fontSize: 13, fontWeight: "800" },
  headerCopy: { flex: 1 },
  headerEyebrow: {
    color: Colors.primary,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  headerTitle: { color: Colors.text, fontSize: 21, fontWeight: "900" },
  modeSwitchWrap: {
    alignSelf: "center",
    maxWidth: 560,
    paddingHorizontal: 16,
    paddingTop: 4,
    width: "100%",
  },
  container: {
    alignSelf: "center",
    maxWidth: 560,
    paddingBottom: 30,
    paddingHorizontal: 16,
    width: "100%",
  },
  introRow: { alignItems: "center", flexDirection: "row", gap: 11, marginTop: 18 },
  stepBadge: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: 11,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
    ...Effects.recessed,
  },
  stepBadgeText: { color: Colors.primary, fontSize: 15, fontWeight: "900" },
  stepCopy: { flex: 1 },
  sectionTitle: { color: Colors.text, fontSize: 18, fontWeight: "900" },
  sectionHint: { color: Colors.textMuted, fontSize: 11, marginTop: 2 },
  choiceRow: { flexDirection: "row", gap: 8, marginTop: 12 },
  choice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 7,
    ...Effects.controlRaised,
  },
  choiceSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  choiceText: { color: Colors.textMuted, fontSize: 11, fontWeight: "800", textAlign: "center" },
  choiceTextSelected: { color: Colors.inverseText },
  sizeChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
    ...Effects.controlRaised,
  },
  sizeChoiceText: { color: Colors.text, fontSize: 15, fontWeight: "900" },
  expandedChoices: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
  expandedChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 10,
    borderWidth: 1,
    minHeight: 42,
    minWidth: 120,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  smallExpandedChoice: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 10,
    borderWidth: 1,
    minHeight: 42,
    minWidth: 66,
    paddingHorizontal: 11,
    justifyContent: "center",
  },
  expandedChoiceSelected: { borderColor: Colors.primary, backgroundColor: Colors.primarySoft },
  expandedChoiceText: { color: Colors.text, fontSize: 12, fontWeight: "800" },
  divider: { backgroundColor: Colors.border, height: StyleSheet.hairlineWidth, marginTop: 20 },
  wireList: { gap: 9, marginTop: 12 },
  wireRow: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 70,
    padding: 8,
    ...Effects.surfaceRaised,
  },
  quantityControl: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 11,
    borderWidth: 1,
    flexDirection: "row",
    overflow: "hidden",
  },
  quantityButton: { alignItems: "center", height: 48, justifyContent: "center", width: 37 },
  quantityButtonText: { color: Colors.primary, fontSize: 20, fontWeight: "900" },
  quantityValue: { alignItems: "center", justifyContent: "center", minWidth: 39 },
  quantityNumber: { color: Colors.text, fontSize: 18, fontWeight: "900", lineHeight: 20 },
  quantityLabel: { color: Colors.textSubtle, fontSize: 7, fontWeight: "900", letterSpacing: 0.7 },
  wireSizeButton: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 11,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 50,
    paddingHorizontal: 12,
  },
  wireSizeLabel: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.7 },
  wireSizeValue: { color: Colors.text, fontSize: 16, fontWeight: "900", marginTop: 2 },
  chevron: { color: Colors.textMuted, fontSize: 16, fontWeight: "900" },
  removeButton: {
    alignItems: "center",
    backgroundColor: Colors.errorSoft,
    borderRadius: 10,
    height: 42,
    justifyContent: "center",
    width: 34,
  },
  removeButtonText: { color: Colors.error, fontSize: 22, fontWeight: "700", lineHeight: 23 },
  addWireButton: {
    alignItems: "center",
    borderColor: Colors.borderStrong,
    borderRadius: 13,
    borderStyle: "dashed",
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginTop: 10,
    minHeight: 48,
  },
  addWireIcon: { color: Colors.primary, fontSize: 19, fontWeight: "900" },
  addWireText: { color: Colors.text, fontSize: 13, fontWeight: "800" },
  resultCard: {
    backgroundColor: "#17251F",
    borderColor: "#486D5D",
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 22,
    padding: 17,
    ...Effects.surfaceRaised,
  },
  resultCardFail: { backgroundColor: Colors.errorSoft, borderColor: Colors.error },
  resultTopRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  resultEyebrow: { color: Colors.textMuted, fontSize: 9, fontWeight: "900", letterSpacing: 1.1 },
  resultStatus: { color: "#76C69E", fontSize: 35, fontWeight: "900", letterSpacing: 0.4 },
  resultStatusFail: { color: Colors.error },
  fillBadge: {
    alignItems: "center",
    backgroundColor: "#223A30",
    borderColor: "#486D5D",
    borderRadius: 13,
    borderWidth: 1,
    minWidth: 74,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  fillBadgeFail: { backgroundColor: "#522C28", borderColor: Colors.error },
  fillBadgeValue: { color: Colors.text, fontSize: 17, fontWeight: "900" },
  fillBadgeLabel: { color: Colors.textMuted, fontSize: 7, fontWeight: "900", letterSpacing: 0.7 },
  meterTrack: {
    backgroundColor: Colors.bg,
    borderRadius: 7,
    height: 12,
    marginTop: 16,
    overflow: "hidden",
    position: "relative",
  },
  meterFill: { backgroundColor: "#62A982", borderRadius: 7, height: "100%" },
  meterFillFail: { backgroundColor: Colors.error },
  meterLimit: { backgroundColor: Colors.primary, height: "100%", position: "absolute", width: 2, zIndex: 2 },
  meterLabels: { flexDirection: "row", justifyContent: "space-between", marginTop: 6 },
  meterLabel: { color: Colors.textMuted, fontSize: 10, fontWeight: "700" },
  resultDetails: {
    borderTopColor: "rgba(255,255,255,0.09)",
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    marginTop: 15,
    paddingTop: 14,
  },
  detailBlock: { flex: 1 },
  detailRule: { backgroundColor: "rgba(255,255,255,0.10)", marginHorizontal: 12, width: 1 },
  detailLabel: { color: Colors.textMuted, fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  detailValue: { color: Colors.text, fontSize: 13, fontWeight: "900", marginTop: 3 },
  codeNote: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 12,
    padding: 13,
  },
  codeNoteTitle: { color: Colors.primary, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 },
  codeNoteText: { color: Colors.textMuted, fontSize: 11, lineHeight: 16, marginTop: 4 },
  pressed: { opacity: 0.78, transform: [{ scale: 0.98 }], ...Effects.pressed },
  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: {
    backgroundColor: "rgba(0,0,0,0.70)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  sheet: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    maxHeight: "78%",
    paddingBottom: 10,
  },
  sheetHandle: { alignSelf: "center", backgroundColor: Colors.borderStrong, borderRadius: 3, height: 4, marginTop: 9, width: 42 },
  sheetHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", padding: 16 },
  sheetEyebrow: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  sheetTitle: { color: Colors.text, fontSize: 20, fontWeight: "900", marginTop: 2 },
  doneButton: { backgroundColor: Colors.primary, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 9 },
  doneButtonText: { color: Colors.inverseText, fontSize: 12, fontWeight: "900" },
  wireSizeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingBottom: 18, paddingHorizontal: 16 },
  wireSizeOption: {
    alignItems: "center",
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: 11,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 48,
    width: "30.8%",
  },
  wireSizeOptionSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  wireSizeOptionText: { color: Colors.text, fontSize: 14, fontWeight: "900" },
  wireSizeOptionTextSelected: { color: Colors.inverseText },
});
