import { StyleSheet } from "react-native";

import { Colors, Effects } from "../../theme";

export const styles = StyleSheet.create({
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: 12,
    maxWidth: 560,
    paddingHorizontal: 16,
    paddingVertical: 10,
    width: "100%",
  },
  homeButton: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 10,
    ...Effects.controlRaised,
  },
  homeButtonText: { color: Colors.text, fontSize: 13, fontWeight: "800" },
  headerCopy: { flex: 1 },
  headerEyebrow: { color: Colors.primary, fontSize: 9, fontWeight: "900", letterSpacing: 1.2 },
  headerTitle: { color: Colors.text, fontSize: 21, fontWeight: "900" },
  container: {
    alignSelf: "center",
    maxWidth: 560,
    paddingBottom: 30,
    paddingHorizontal: 16,
    width: "100%",
  },
  promptRow: { alignItems: "center", flexDirection: "row", gap: 12, marginTop: 8 },
  wireGlyph: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: 16,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    overflow: "hidden",
    width: 48,
    ...Effects.recessed,
  },
  wireCore: {
    backgroundColor: Colors.primary,
    borderColor: "#F6C55E",
    borderRadius: 4,
    borderWidth: 1,
    height: 30,
    transform: [{ rotate: "20deg" }],
    width: 8,
  },
  promptCopy: { flex: 1 },
  promptTitle: { color: Colors.text, fontSize: 20, fontWeight: "900" },
  promptHint: { color: Colors.textMuted, fontSize: 11, marginTop: 2 },
  segmented: {
    backgroundColor: "#0E1216",
    borderColor: Colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 5,
    marginTop: 16,
    padding: 4,
    ...Effects.recessed,
  },
  segment: {
    alignItems: "center",
    borderRadius: 10,
    flex: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 46,
  },
  segmentSelected: { backgroundColor: Colors.surface3, ...Effects.controlRaised },
  segmentText: { color: Colors.textMuted, fontSize: 13, fontWeight: "800" },
  segmentTextSelected: { color: Colors.text },
  materialDot: {
    backgroundColor: "#B66F38",
    borderColor: "#E0A06B",
    borderRadius: 6,
    borderWidth: 1,
    height: 11,
    width: 11,
  },
  materialDotAluminum: { backgroundColor: "#9DA7AF", borderColor: "#D7DEE3" },
  sectionHeading: { marginTop: 19 },
  sectionTitle: { color: Colors.text, fontSize: 16, fontWeight: "900" },
  sectionHint: { color: Colors.textMuted, fontSize: 10, marginTop: 2 },
  sizeRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 },
  sizeButton: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 11,
    borderWidth: 1,
    flexGrow: 1,
    justifyContent: "center",
    minHeight: 47,
    minWidth: 54,
    paddingHorizontal: 8,
    ...Effects.controlRaised,
  },
  otherSizeButton: { minWidth: 76 },
  sizeButtonSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary, ...Effects.primaryRaised },
  sizeButtonText: { color: Colors.text, fontSize: 14, fontWeight: "900" },
  sizeButtonTextSelected: { color: Colors.inverseText },
  otherSizeText: { color: Colors.textMuted, fontSize: 11, fontWeight: "800" },
  connectionCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 11,
    marginTop: 14,
    minHeight: 70,
    padding: 12,
    ...Effects.surfaceRaised,
  },
  connectionIcon: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderColor: Colors.borderStrong,
    borderRadius: 11,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
    ...Effects.recessed,
  },
  connectionIconText: { color: "#AFC3D6", fontSize: 13, fontWeight: "900" },
  connectionCopy: { flex: 1 },
  connectionLabel: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 0.9 },
  connectionValue: { color: Colors.text, fontSize: 15, fontWeight: "900", marginTop: 2 },
  connectionHint: { color: Colors.textMuted, fontSize: 9, marginTop: 2 },
  chevron: { color: Colors.textMuted, fontSize: 19, fontWeight: "900" },
  resultCard: {
    backgroundColor: "#171E26",
    borderColor: Colors.primaryMuted,
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 16,
    overflow: "hidden",
    padding: 17,
    position: "relative",
    ...Effects.surfaceRaised,
  },
  resultGlow: {
    backgroundColor: "rgba(224,165,38,0.08)",
    borderRadius: 110,
    height: 160,
    position: "absolute",
    right: -65,
    top: -80,
    width: 160,
  },
  resultTopRow: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" },
  resultEyebrow: { color: Colors.primary, fontSize: 9, fontWeight: "900", letterSpacing: 1.1 },
  ampRow: { alignItems: "baseline", flexDirection: "row", gap: 7, marginTop: -3 },
  ampValue: { color: Colors.text, fontSize: 62, fontWeight: "900", letterSpacing: -2 },
  ampUnit: { color: Colors.primary, fontSize: 27, fontWeight: "900" },
  resultWireBadge: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: 13,
    borderWidth: 1,
    minWidth: 70,
    paddingHorizontal: 10,
    paddingVertical: 9,
    ...Effects.recessed,
  },
  resultWireSize: { color: Colors.text, fontSize: 16, fontWeight: "900" },
  resultWireMaterial: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1, marginTop: 2 },
  limitStrip: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: Colors.surface3,
    borderColor: Colors.borderStrong,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    marginTop: 2,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  limitDot: { backgroundColor: Colors.primary, borderRadius: 4, height: 7, width: 7 },
  limitText: { color: Colors.text, fontSize: 10, fontWeight: "800" },
  resultContext: { color: Colors.textMuted, fontSize: 9, lineHeight: 14, marginTop: 10 },
  breakdownButton: {
    alignItems: "center",
    borderTopColor: Colors.border,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 13,
    minHeight: 42,
    paddingTop: 10,
  },
  breakdownButtonText: { color: "#AFC3D6", fontSize: 11, fontWeight: "900" },
  breakdown: {
    backgroundColor: "#11171D",
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    gap: 9,
    marginTop: 5,
    padding: 12,
    ...Effects.recessed,
  },
  breakdownRow: { alignItems: "center", flexDirection: "row", gap: 10, justifyContent: "space-between" },
  breakdownLabel: { color: Colors.textMuted, flex: 1, fontSize: 9, lineHeight: 13 },
  breakdownValue: { color: Colors.text, fontSize: 10, fontWeight: "800" },
  breakdownRule: { backgroundColor: Colors.border, height: 1 },
  breakdownEmphasis: { color: Colors.text, fontWeight: "900" },
  breakdownValueEmphasis: { color: Colors.primary, fontSize: 12 },
  advancedHeader: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    marginTop: 14,
    minHeight: 63,
    paddingHorizontal: 14,
    paddingVertical: 10,
    ...Effects.controlRaised,
  },
  advancedHeaderCopy: { flex: 1 },
  advancedEyebrow: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 0.9 },
  advancedTitle: { color: Colors.text, fontSize: 14, fontWeight: "900", marginTop: 2 },
  activeBadge: { backgroundColor: Colors.primary, borderRadius: 7, paddingHorizontal: 7, paddingVertical: 4 },
  activeBadgeText: { color: Colors.inverseText, fontSize: 8, fontWeight: "900" },
  advancedCard: {
    backgroundColor: Colors.surface2,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderColor: Colors.border,
    borderTopWidth: 0,
    borderWidth: 1,
    marginHorizontal: 5,
    padding: 10,
  },
  settingRow: { alignItems: "center", flexDirection: "row", gap: 8, minHeight: 57, paddingHorizontal: 5 },
  settingCopy: { flex: 1 },
  settingLabel: { color: Colors.text, fontSize: 12, fontWeight: "900" },
  settingHint: { color: Colors.textMuted, fontSize: 9, marginTop: 2 },
  settingValue: { color: Colors.primary, fontSize: 11, fontWeight: "900" },
  settingRule: { backgroundColor: Colors.border, height: 1 },
  advancedHelp: {
    backgroundColor: "#171D24",
    borderRadius: 9,
    color: Colors.textMuted,
    fontSize: 9,
    lineHeight: 14,
    marginTop: 7,
    padding: 10,
  },
  resetButton: { alignItems: "center", minHeight: 42, justifyContent: "center", marginTop: 5 },
  resetButtonText: { color: Colors.primary, fontSize: 10, fontWeight: "900" },
  referenceNote: {
    backgroundColor: "#171D24",
    borderColor: Colors.border,
    borderRadius: 13,
    borderWidth: 1,
    marginTop: 15,
    padding: 13,
  },
  referenceTitle: { color: Colors.textSubtle, fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  referenceText: { color: Colors.textMuted, fontSize: 9, lineHeight: 14, marginTop: 5 },
  pressed: { opacity: 0.82, transform: [{ scale: 0.985 }], ...Effects.pressed },

  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: { backgroundColor: "rgba(0,0,0,0.72)", ...StyleSheet.absoluteFill },
  sheet: {
    backgroundColor: Colors.bg,
    borderColor: Colors.borderStrong,
    borderTopLeftRadius: 23,
    borderTopRightRadius: 23,
    borderWidth: 1,
    maxHeight: "86%",
    minHeight: 260,
    paddingBottom: 14,
    paddingHorizontal: 16,
    ...Effects.surfaceRaised,
  },
  sheetHandle: {
    alignSelf: "center",
    backgroundColor: Colors.borderStrong,
    borderRadius: 3,
    height: 4,
    marginBottom: 12,
    marginTop: 8,
    width: 40,
  },
  sheetHeader: { alignItems: "center", flexDirection: "row", gap: 12, marginBottom: 12 },
  sheetHeadingCopy: { flex: 1 },
  sheetEyebrow: { color: Colors.primary, fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  sheetTitle: { color: Colors.text, fontSize: 20, fontWeight: "900", marginTop: 2 },
  doneButton: {
    backgroundColor: Colors.primary,
    borderRadius: 10,
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 9,
    ...Effects.primaryRaised,
  },
  doneButtonText: { color: Colors.inverseText, fontSize: 11, fontWeight: "900", textAlign: "center" },
  sizeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingBottom: 10 },
  sheetSizeOption: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 11,
    borderWidth: 1,
    flexBasis: "22%",
    flexGrow: 1,
    justifyContent: "center",
    minHeight: 50,
    ...Effects.controlRaised,
  },
  sheetSizeText: { color: Colors.text, fontSize: 13, fontWeight: "900" },
  sheetOptionSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  sheetOptionTextSelected: { color: Colors.primary },
  optionList: { gap: 8, paddingBottom: 10 },
  sheetOption: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 58,
    paddingHorizontal: 13,
    paddingVertical: 9,
    ...Effects.controlRaised,
  },
  sheetOptionCopy: { flex: 1 },
  sheetOptionTitle: { color: Colors.text, fontSize: 13, fontWeight: "900" },
  sheetOptionHint: { color: Colors.textMuted, fontSize: 9, lineHeight: 13, marginTop: 2 },
  sheetCheck: { color: Colors.primary, fontSize: 17, fontWeight: "900" },
  sheetHelp: { color: Colors.textMuted, fontSize: 9, lineHeight: 14, paddingHorizontal: 5, paddingTop: 4 },
});
