import { Layout , Space , Radius, FontSize, Fonts } from "../../theme/tokens";
import { defineStyles } from "../../theme";
import { ReferenceColors } from "../../theme/color";
import { StyleSheet } from "react-native";

export const useStyles = defineStyles(({ colors: Colors }) => ({
  safe: { backgroundColor: Colors.bg, flex: 1 },
  header: {
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
    gap: Space.sm,
    maxWidth: Layout.contentWidth,
    paddingHorizontal: Space.md,
    paddingVertical: 10,
    width: "100%",
  },
  homeButton: {
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 10,

  },
  homeButtonText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  headerCopy: { flex: 1 },
  headerEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.2 },
  headerTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500" },
  container: {
    alignSelf: "center",
    maxWidth: Layout.contentWidth,
    paddingBottom: 30,
    paddingHorizontal: Space.md,
    width: "100%",
  },
  promptRow: { alignItems: "center", flexDirection: "row", gap: Space.sm, marginTop: Space.xs },
  wireGlyph: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.card,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    overflow: "hidden",
    width: 48,

  },
  wireCore: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    borderRadius: 4,
    borderWidth: 1,
    height: 30,
    transform: [{ rotate: "20deg" }],
    width: 8,
  },
  promptCopy: { flex: 1 },
  promptTitle: { color: Colors.text, fontSize: FontSize.section, fontWeight: "500" },
  promptHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  segmented: {
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: 5,
    marginTop: Space.md,
    padding: Space.xxs,

  },
  segment: {
    alignItems: "center",
    borderRadius: Radius.control,
    flex: 1,
    flexDirection: "row",
    gap: Space.xs,
    justifyContent: "center",
    minHeight: 46,
  },
  segmentSelected: { backgroundColor: Colors.surface3,  },
  segmentText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  segmentTextSelected: { color: Colors.text },
  materialDot: {
    backgroundColor: ReferenceColors.colorB66F38,
    borderColor: ReferenceColors.colorE0A06B,
    borderRadius: 6,
    borderWidth: 1,
    height: 11,
    width: 11,
  },
  materialDotAluminum: { backgroundColor: ReferenceColors.color9DA7AF, borderColor: ReferenceColors.colorD7DEE3 },
  sectionHeading: { marginTop: 19 },
  sectionTitle: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500" },
  sectionHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  sizeRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 },
  sizeButton: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexGrow: 1,
    justifyContent: "center",
    minHeight: 47,
    minWidth: 54,
    paddingHorizontal: Space.xs,

  },
  otherSizeButton: { minWidth: 76 },
  sizeButtonSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary,  },
  sizeButtonText: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500" },
  sizeButtonTextSelected: { color: Colors.inverseText },
  otherSizeText: { color: Colors.textMuted, fontSize: FontSize.caption, fontWeight: "500" },
  connectionCard: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: 11,
    marginTop: 14,
    minHeight: 70,
    padding: Space.sm,

  },
  connectionIcon: {
    alignItems: "center",
    backgroundColor: Colors.surface3,
    borderColor: Colors.borderStrong,
    borderRadius: Radius.control,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,

  },
  connectionIconText: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  connectionCopy: { flex: 1 },
  connectionLabel: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.9 },
  connectionValue: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500", marginTop: 2 },
  connectionHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  chevron: { color: Colors.textMuted, fontSize: FontSize.subtitle, fontWeight: "500" },
  resultCard: {
    backgroundColor: Colors.surface,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.large,
    borderWidth: 1,
    marginTop: Space.md,
    overflow: "hidden",
    padding: 17,
    position: "relative",

  },
  resultGlow: {
    backgroundColor: Colors.border,
    borderRadius: Radius.round,
    height: 160,
    position: "absolute",
    right: -65,
    top: -80,
    width: 160,
  },
  resultTopRow: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" },
  resultEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1.1 },
  ampRow: { alignItems: "baseline", flexDirection: "row", gap: 7, marginTop: -3 },
  ampValue: { color: Colors.text, fontSize: FontSize.hero, fontWeight: "500", letterSpacing: -2 },
  ampUnit: { color: Colors.primary, fontSize: FontSize.heading, fontWeight: "500" },
  resultWireBadge: {
    alignItems: "center",
    backgroundColor: Colors.primarySoft,
    borderColor: Colors.primaryMuted,
    borderRadius: Radius.control,
    borderWidth: 1,
    minWidth: 70,
    paddingHorizontal: 10,
    paddingVertical: 9,

  },
  resultWireSize: { color: Colors.text, fontSize: FontSize.body, fontWeight: "500" },
  resultWireMaterial: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1, marginTop: 2 },
  limitStrip: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: Colors.surface3,
    borderColor: Colors.borderStrong,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    marginTop: 2,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  limitDot: { backgroundColor: Colors.primary, borderRadius: 4, height: 7, width: 7 },
  limitText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  resultContext: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 14, marginTop: 10 },
  breakdownButton: {
    alignItems: "center",
    borderTopColor: Colors.border,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 13,
    minHeight: 42,
    paddingTop: 10,
  },
  breakdownButtonText: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  breakdown: {
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    gap: 9,
    marginTop: 5,
    padding: Space.sm,

  },
  breakdownRow: { alignItems: "center", flexDirection: "row", gap: 10, justifyContent: "space-between" },
  breakdownLabel: { color: Colors.textMuted, flex: 1, fontSize: FontSize.caption, lineHeight: 13 },
  breakdownValue: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  breakdownRule: { backgroundColor: Colors.border, height: 1 },
  breakdownEmphasis: { color: Colors.text, fontWeight: "500" },
  breakdownValueEmphasis: { color: Colors.primary, fontSize: FontSize.caption },
  advancedHeader: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    marginTop: 14,
    minHeight: 63,
    paddingHorizontal: 14,
    paddingVertical: 10,

  },
  advancedHeaderCopy: { flex: 1 },
  advancedEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 0.9 },
  advancedTitle: { color: Colors.text, fontSize: FontSize.label, fontWeight: "500", marginTop: 2 },
  activeBadge: { backgroundColor: Colors.primary, borderRadius: 7, paddingHorizontal: 7, paddingVertical: Space.xxs },
  activeBadgeText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500" },
  advancedCard: {
    backgroundColor: Colors.surface2,
    borderBottomLeftRadius: Radius.card,
    borderBottomRightRadius: Radius.card,
    borderColor: Colors.border,
    borderTopWidth: 0,
    borderWidth: 1,
    marginHorizontal: 5,
    padding: 10,
  },
  settingRow: { alignItems: "center", flexDirection: "row", gap: Space.xs, minHeight: 57, paddingHorizontal: 5 },
  settingCopy: { flex: 1 },
  settingLabel: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  settingHint: { color: Colors.textMuted, fontSize: FontSize.caption, marginTop: 2 },
  settingValue: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  settingRule: { backgroundColor: Colors.border, height: 1 },
  advancedHelp: {
    backgroundColor: Colors.surface2,
    borderRadius: Radius.small,
    color: Colors.textMuted,
    fontSize: FontSize.caption,
    lineHeight: 14,
    marginTop: 7,
    padding: 10,
  },
  resetButton: { alignItems: "center", minHeight: 42, justifyContent: "center", marginTop: 5 },
  resetButtonText: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500" },
  referenceNote: {
    backgroundColor: Colors.surface2,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    marginTop: 15,
    padding: 13,
  },
  referenceTitle: { color: Colors.textSubtle, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1 },
  referenceText: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 14, marginTop: 5 },
  pressed: { opacity: 0.82, transform: [{ scale: 0.985 }],  },

  modalSafe: { flex: 1, justifyContent: "flex-end" },
  modalScrim: { backgroundColor: Colors.overlay, ...StyleSheet.absoluteFill },
  sheet: {
    backgroundColor: Colors.bg,
    borderColor: Colors.borderStrong,
    borderTopLeftRadius: Radius.sheet,
    borderTopRightRadius: Radius.sheet,
    borderWidth: 1,
    maxHeight: "86%",
    minHeight: 260,
    paddingBottom: 14,
    paddingHorizontal: Space.md,

  },
  sheetHandle: {
    alignSelf: "center",
    backgroundColor: Colors.borderStrong,
    borderRadius: 3,
    height: 4,
    marginBottom: Space.sm,
    marginTop: Space.xs,
    width: 40,
  },
  sheetHeader: { alignItems: "center", flexDirection: "row", gap: Space.sm, marginBottom: Space.sm },
  sheetHeadingCopy: { flex: 1 },
  sheetEyebrow: { color: Colors.primary, fontSize: FontSize.caption, fontWeight: "500", letterSpacing: 1 },
  sheetTitle: { fontFamily: Fonts.heading, color: Colors.text, fontSize: FontSize.section, fontWeight: "500", marginTop: 2 },
  doneButton: {
    backgroundColor: Colors.primary,
    borderRadius: Radius.control,
    minWidth: 58,
    paddingHorizontal: Space.sm,
    paddingVertical: 9,

  },
  doneButtonText: { color: Colors.inverseText, fontSize: FontSize.caption, fontWeight: "500", textAlign: "center" },
  sizeGrid: { flexDirection: "row", flexWrap: "wrap", gap: Space.xs, paddingBottom: 10 },
  sheetSizeOption: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexBasis: "22%",
    flexGrow: 1,
    justifyContent: "center",
    minHeight: 50,

  },
  sheetSizeText: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  sheetOptionSelected: { backgroundColor: Colors.primarySoft, borderColor: Colors.primary },
  sheetOptionTextSelected: { color: Colors.primary },
  optionList: { gap: Space.xs, paddingBottom: 10 },
  sheetOption: {
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderColor: Colors.border,
    borderRadius: Radius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 58,
    paddingHorizontal: 13,
    paddingVertical: 9,

  },
  sheetOptionCopy: { flex: 1 },
  sheetOptionTitle: { color: Colors.text, fontSize: FontSize.caption, fontWeight: "500" },
  sheetOptionHint: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 13, marginTop: 2 },
  sheetCheck: { color: Colors.primary, fontSize: FontSize.body, fontWeight: "500" },
  sheetHelp: { color: Colors.textMuted, fontSize: FontSize.caption, lineHeight: 14, paddingHorizontal: 5, paddingTop: Space.xxs },
}));
